mozilla/cbindgen

src/bindgen/items.rs
Translating `*const *const my_type` ptr to c/c++ resulted in invalid code(`const const my_type**`)
=> Fix handling of *const *const ptr

src/bindgen/items.rs, src/bindgen/rename.rs, src/bindgen/rust_lib.rs
This adds support for a new rename rule `QualifiedScreamingSnakeCase` for #20.
The difference to `ScreamingSnakeCase` is that enum variants are prefixed with the enum type.
=> Added QualifiedScreamingSnakeCase

src/bindgen/cdecl.rs, src/bindgen/config.rs, src/bindgen/ir/alias.rs, src/bindgen/ir/documentation.rs, src/bindgen/ir/enumeration.rs, src/bindgen/ir/function.rs, src/bindgen/ir/mod.rs, src/bindgen/ir/opaque.rs, src/bindgen/ir/structure.rs, src/bindgen/ir/ty.rs, src/bindgen/library.rs, src/bindgen/utilities.rs
This adds an option to translate rust doc comments into documentation
comments in the generated c/c++ header. 
For example the following code is translated into the following header:
```rust
/// This is the color enum
#[repr(u8)]
pub enum Color {
/// Red color
Red = 1,
Blue = 2,
}
/// This is the color struct
#[repr(C)]
pub struct ColorStruct {
/// A field storing the color of the struct
my_color: Color,
}
/// A function taking the color struct
#[no_mangle]
extern "C" fn take_color_struct(a: ColorStruct) {}
```
```C++
// This is the color enum
enum class Color: uint8_t {
// Red color
Red = 1;
Blue = 2;
};
// This is the color struct
struct ColorStruct {
// A field storing the color of the struct
Color my_color;
};
// A function taking the color struct
void take_color_struct(ColorStruct …
```
=> Allow to translate doc comments

src/bindgen/config.rs, src/bindgen/ir/enumeration.rs
This is mostly usefull for generated c headers because enums values
will live in the global namespace there
With this option enabled for the following code
```rust
#[repr(u8)]
pub enum Color {
Red = 1,
Blue = 2,
}
```
the following C Header is generated
```C
enum Color {
Color_Red = 1,
Color_Blue = 2,
};
typedef uint8_t Color;
```
=> Add a option the prefix enum values by the enum name

Cargo.toml
I've noticed that running `cargo doc` can't build the documentation because the binary and its backing library have the same name. It's not really useful to document the binary, so I've told cargo to ignore it. Otherwise running `cargo doc` spits out an error like this:
```
error: cannot document a package where a library and a binary have the same name. Consider renaming one or marking the target as `doc = false`
```
=> Made it so `cargo doc` can generate docs for the library

src/bindgen/bindings.rs, src/bindgen/ir/documentation.rs
I picked one code style for C comments here that seems well established in C land. There might be better ones but that one was also pretty simple and straightforward to implement without needing special handling.
This fixes https://github.com/eqrion/cbindgen/issues/59
=> Use C-style comments in C mode

src/bindgen/rename.rs
This correctly converts `enum Foo { X }` to `FOO_X` instead of
the current `FOO_x` which is what currently happens.
(I provided the original patch that landed the functionality but I missed the incorrect behavior)
=> Fix incorrectly implemented QualifiedScreamingSnakeCase

src/bindgen/ir/annotation.rs, src/bindgen/ir/documentation.rs
I'm not sure if this is the best way to fix it, but this seems to work quite well. I have no idea how this is supposed to work but obviously one could also fix this in sym.
This fixes https://github.com/eqrion/cbindgen/issues/60
=> Implement doc handling for macro expansion

src/bindgen/cargo/cargo.rs
See also: 594cb21 and #27 
This covers all crate types except for `bin` and `proc-macro`.
=> Also generate headers for rlib crates

src/main.rs
This is useful for scripts and such to abort on errors
=> Exit with an error code on failure

src/bindgen/cargo/cargo.rs
Since cargo allows '-' in crate names, but rust source changes it to '_', cbindgen wasn't finding crates that were named like 'some-crate', since it was looking for 'some_crate' in the Cargo.lock. This does a find/replace on the crate name and searches for both versions of the name.
=> Look for -/_ replaced crates

src/bindgen/ir/enumeration.rs
When declared as `#[repr(C)]`, enums are currently declared as
```C
enum Foo {
...
};
```
but show up in function arguments as
```C
void bar(Foo arg);
```
which isn't valid because it's missing the `enum` specifier.
Rather than insert it there, I followed the convention for struct declarations and made `#[repr(C)]` enums get declared as
```C
typedef enum {
...
} Foo;
```
Enums that are declared as `#[repr(<size>)]` and were previously typedef'd should remain unchanged.
=> Use typedef for C enums as for structs

src/bindgen/rust_lib.rs
If a crate is imported as `extern dependency as some_other_name;`, cbindgen fails to find it with a `can't find version for some_other_name` error message. The syn `ExternCrate` node comes with an optional alias, so use that when looking for a dependency crate if it exists.
=> Support extern crate ... as ...; imports

compile-tests/enum.rs, src/bindgen/ir/enumeration.rs, src/bindgen/ir/repr.rs
There some enums use repr(usize) and repr(isize) in rust std. Try to use intptr_t and uintptr_t[1] for these enums.
[1]
http://www.cplusplus.com/reference/cstdint/
=> Support repr(usize) and repr(isize) enum.

src/bindgen/cargo/cargo_expand.rs
Addresses part of #72 
Permits defining an override for the `CARGO_TARGET_DIR` variable when running cargo-expand. I used a separate variable `CARGO_EXPAND_TARGET_DIR` so as not to overload `CARGO_TARGET_DIR` in a build script, for example.
=> Allow CARGO_TARGET_DIR override in cargo_expand

src/bindgen/bindings.rs, src/bindgen/cdecl.rs, src/bindgen/ir/cfg.rs, src/bindgen/ir/constant.rs, src/bindgen/ir/documentation.rs, src/bindgen/ir/enumeration.rs, src/bindgen/ir/function.rs, src/bindgen/ir/global.rs, src/bindgen/ir/opaque.rs, src/bindgen/ir/structure.rs, src/bindgen/ir/union.rs, src/bindgen/writer.rs
Allows to use write! macro on SourceWriter and so avoid allocation and construction of temporary Strings for dynamically constructed output.
.write method can still be used for static strings as a convenience.
=> Add write_fmt to SourceWriter

src/bindgen/ir/opaque.rs, tests/expectations/enum.c, tests/expectations/monomorph-1.c, tests/expectations/monomorph-2.c, tests/expectations/monomorph-3.c, tests/expectations/simplify-option-ptr.c, tests/expectations/static.c, tests/expectations/std_lib.c, tests/expectations/struct.c, tests/expectations/union.c
There is no need for a separate forward struct declaration, just like in case with regular structures.
=> Simplify opaque struct output in C

src/bindgen/ir/enumeration.rs
In C++, output already uses enum classes so enum variants are only accessible via enum name `E::A` and there is no point in manually prefixing them again to make it `E::E_A`.
C uses global scope for all enum variants, so transformation continues to work as it did.
I realise this change might be somewhat controversial, but it seems reasonable to me and would like to hear concerns if any.
=> Don't prefix enum variants with name in C++

src/bindgen/bindings.rs
This PR eliminates some conversion, i.e., this code:
```rust
let header_path = PathBuf::from(env::var("OUT_DIR").unwrap()).join("bindings.h");
let header_path_str = header_path.to_str().unwrap();
generator.write_to_file(header_path_str);
```
reduces to:
```rust
let header_path = PathBuf::from(env::var("OUT_DIR").unwrap()).join("bindings.h");
generator.write_to_file(header_path);
```
I do not think this affects existing code because [File::open](https://doc.rust-lang.org/std/fs/struct.File.html#method.open) works the same.
=> Require Path instead of &str for write_to_file()

src/bindgen/cdecl.rs, src/bindgen/ir/function.rs, tests/expectations/cdecl.c, tests/expectations/extern-2.c, tests/expectations/extern.c, tests/expectations/static.c
`fun test() -> bool` was declared as `bool test();`.
Omitting the list of arguments in the prototype instructs the compiler to allow any type of arguments in the declaration of the `test` function. `bool test(void)` in C is equivalent to `bool test()` in C++ and will only allow declarations without arguments.
GCC warns about this with the `-Wstrict-prototype` flag set.
This change only affects `Language::C`. AFAIK the current C++ behavior is prefered.
=> Emit correct prototypes for functions without arguments in C mode

src/bindgen/parser.rs
I was getting a parse error on webrender and there was insufficient context to figure out what was going on.
=> Increase parse error message to include more context

src/bindgen/ir/structure.rs, src/bindgen/ir/union.rs
I found that the presence of an
```toml
[export]
prefix = "Foo"
```
section in the config would cause errors in monomorphizatoin.
Given a rust struct definition like
```rust
#[repr(C)]
pub struct Bar<T> {
f: T,
}
#[no_mangle]
pub extern "C" fn take_bar(foo: Bar<usize>) {}
```
without the prefix option, you get the C struct:
```C
typedef struct {
uintptr_t f;
} Bar_usize;
```
but with the prefix, you get
```C
typedef struct {
FooT f;
} Bar_usize;
```
Which results in undefined type errors for `FooT`.
My investigation led me to the conclusion that `<Struct as Item>::rename_for_config` was overeager in renaming field types and applied renaming rules regardless of whether or not the type was actually a generic type parameter. I simply inserted a check for this, and the problem went away.
As a …
=> Don't apply renaming to generic type parameters

.travis.yml, Cargo.lock, Cargo.toml, src/lib.rs, src/main.rs
This updates cbindgen to use standalone-syn which in turn uses standalone-quote and standalone-proc-macro2, all of which use rustc-ap-proc_macro, which is a fork of the libproc_macro in rustc. This is a workaround for rust-lang/rust#47931 which allows the cbindgen binary to run without requiring all users to hack the LD_LIBRARY_PATH to pick up rustc internal dynamic libraries.
=> Free cbindgen from rustc-internal dynamic lib dependencies

src/bindgen/builder.rs, src/bindgen/cargo/cargo.rs, src/main.rs
Fixes #141.
For projects in workspaces, the Cargo.lock file may not be in the same
folder as Cargo.toml. This patch allows the user to explicitly pass the
path to the Cargo.lock file so that this scenario can be handled.
r? @eqrion
=> Add an option to specify the lockfile

src/bindgen/ir/constant.rs, tests/expectations/cfg-2.c, tests/expectations/cfg-2.cpp, tests/rust/cfg-2.rs
When writing out constants the cfg attribute is not written out around
the defined constant.
=> Ensure that a constants cfg is preserved

src/bindgen/parser.rs, tests/expectations/mod_path.c, tests/expectations/mod_path.cpp, tests/rust/mod_path/Cargo.lock, tests/rust/mod_path/Cargo.toml, tests/rust/mod_path/cbindgen.toml, tests/rust/mod_path/src/lib.rs, tests/rust/mod_path/src/other.rs
If a module has a path attribute use this as the module path to parse.
=> Improve module path parsing

Cargo.lock, Cargo.toml, src/lib.rs, src/main.rs
The new syn/quote (with the proc-macro dependency extracted as an optional feature) is on crates.io now, so we can switch back to using that.
=> Switch back to mainline syn instead of using standalone-syn

README.md
Makes the command example easier to read (imo).
=> Make CLI example more prominent in README.md

src/bindgen/config.rs, src/bindgen/ir/enumeration.rs, tests/expectations/annotation.c, tests/expectations/annotation.cpp, tests/expectations/both/annotation.c, tests/expectations/tag/annotation.c, tests/rust/annotation.rs
This is the most important part of what I proposed in #162
Minor "bug": the convenience constructor names will be the tag names, which means if you're using the prefix name, you'll end up with static constructor names like `MyEnum_CaseA()`. This is awkward to avoid under the current design, as the original variant name is completely overwritten by `Item::rename_for_config`, and the snake_case version of the name is only stored if the variant has a body.
WIP because I kinda just hacked this together and am interested in opinions from the maintainers on implementation details. There's possibly some interesting refactoring that could be done to share code with struct ctor generation, but it seemed like it would be more complicated/messy than just duplicating a bit of logic.
Also I added some …
=> Implement optional convenience constructors for tagged enums

README.md, src/bindgen/bindings.rs, src/bindgen/config.rs, src/bindgen/library.rs, tests/expectations/both/item_types.c, tests/expectations/cfg-field.cpp, tests/expectations/global_attr.cpp, tests/expectations/include.cpp, tests/expectations/include_item.cpp, tests/expectations/item_types.c, tests/expectations/item_types.cpp, tests/expectations/nested_import.cpp, tests/expectations/tag/item_types.c, tests/rust/item_types.rs, tests/rust/item_types.toml
I'm going to need this for the style system, otherwise we generate a bunch of constants and such that we don't need.
Also I fixed a stylistic nit where the warning message was printed redundantly, and avoided generating empty extern blocks.
=> Add more control over the generated items.

src/bindgen/cargo/cargo.rs, src/bindgen/cargo/cargo_metadata.rs, tests/expectations/both/external_workspace_child.c, tests/expectations/both/workspace.c, tests/expectations/external_workspace_child.c, tests/expectations/external_workspace_child.cpp, tests/expectations/tag/external_workspace_child.c, tests/expectations/tag/workspace.c, tests/expectations/workspace.c, tests/expectations/workspace.cpp, tests/rust/external_workspace_child/Cargo.toml, tests/rust/external_workspace_child/cbindgen.toml, tests/rust/external_workspace_child/src/lib.rs, tests/rust/workspace/Cargo.lock, tests/rust/workspace/Cargo.toml, tests/rust/workspace/cbindgen.toml, tests/rust/workspace/dep/Cargo.toml, tests/rust/workspace/dep/src/lib.rs, tests/rust/workspace/src/lib.rs
cbindgen currently assumes that the `Cargo.lock` is in directly in the
crate directory as a sibling to `Cargo.toml`; however that is usually
not the case inside a workspace.
Instead, this PR extracts the workspace root from the output of `cargo
metadata` [1] (already used to get a list of packages) and uses the
`Cargo.lock` from there.
1. This is available since Rust 1.24; see rust-lang/cargo#4940
=> Use Cargo.lock from workspace root

src/bindgen/cdecl.rs, src/bindgen/ir/ty.rs, tests/expectations/both/prefix.c, tests/expectations/prefix.c, tests/expectations/prefix.cpp, tests/expectations/tag/prefix.c, tests/rust/prefix.rs, tests/rust/prefix.toml
Fixes https://github.com/eqrion/cbindgen/issues/186.
cc @emilio
=> Fixed missing prefix for named consts in `[T; <Const>]` types

src/bindgen/ir/cfg.rs, src/bindgen/ir/constant.rs, src/bindgen/ir/enumeration.rs, src/bindgen/ir/function.rs, src/bindgen/ir/opaque.rs, src/bindgen/ir/structure.rs, src/bindgen/ir/typedef.rs, src/bindgen/ir/union.rs, tests/expectations/both/mod_attr.c, tests/expectations/mod_attr.c, tests/expectations/mod_attr.cpp, tests/expectations/tag/mod_attr.c, tests/rust/mod_attr/Cargo.lock, tests/rust/mod_attr/Cargo.toml, tests/rust/mod_attr/cbindgen.toml, tests/rust/mod_attr/src/lib.rs
Fixes https://github.com/eqrion/cbindgen/issues/175.
<details open>
```toml
[defines]
"foo" = "FOO"
"bar" = "BAR"
```
</details>
<details open>
```rust
// lib.rs
#[cfg(foo)]
pub const FOO: i32 = 1;
#[cfg(foo)]
#[no_mangle]
pub unsafe extern "C" fn foo(dw: &Foo) {}
#[cfg(foo)]
#[repr(C)]
pub struct Foo {}
#[cfg(feature = "foobar")]
pub mod foo {
#[cfg(bar)]
pub const BAR: i32 = 2;
#[cfg(bar)]
#[no_mangle]
pub unsafe extern "C" fn bar(dnw: &Bar) {}
#[cfg(bar)]
#[repr(C)]
pub struct Bar {}
}
```
</details>
Before this PR:
<details open>
```c
// lib.h
#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>
#define BAR 2
#if defined(FOO)
#define FOO 1
#endif
typedef struct {
} Bar;
#if defined(FOO)
typedef struct {
} Foo;
#endif
void bar(const Bar *dnw);
#if defined(FOO)
void foo(const …
```
=> Fix "Missing `#if defined(…) … #endif` guards in header of items from behind `#[cfg(…)]`"

src/bindgen/error.rs
When I hit this, I initially started bisecting my changes to see where the error
was.
It'd be much nicer if somebody had told me that `rustc -Z parse-only` existed.
=> Point to a solution when we hit a parse error.

Cargo.lock, Cargo.toml, src/bindgen/cargo/cargo_expand.rs, src/logging.rs
- The log dependency was outdated and ported to log 0.4
- tempdir is deprecated and was replaced with tempfile
A new release would be appreciated since the patch is quite large to carry it in debian for the firefox 63 release.
=> Replace outdated dependencies

src/bindgen/parser.rs, src/bindgen/utilities.rs
Fixes https://github.com/eqrion/cbindgen/issues/138.
Note: This does not recognize more advanced patterns like `#[cfg_attr(…, cfg(test))]` or `#[cfg_attr(…, test)]`, but those probably sum up to at most ~1%-ish of usages anyway (and the logic could be extended to also recognize those).
=> Fix "Ignore [cfg(test)] …"

Cargo.lock, Cargo.toml
This will in turn build with `syn 0.13` and `quote 0.5`, which is still
distinct from cbindgen's own dependencies, so it won't get "infected" by
the proc-macro feature.
=> Bump to serde_derive 1.0.58

src/bindgen/bindings.rs, src/bindgen/builder.rs, src/bindgen/config.rs, tests/expectations/both/no_includes.c, tests/expectations/no_includes.c, tests/expectations/no_includes.cpp, tests/expectations/tag/no_includes.c, tests/rust/no_includes.rs, tests/rust/no_includes.toml
Python's cffi can't handle include directives, which is why milksnake and pyo3-pack currently need to strip the includes from the header before they can use it. This pull request introduces a `no_includes` flag which simply disables the part that would normally write the includes.
I'm not sure if the flags should only disable the default includes (`stdint.h`/`stdlib.h`/`stdbool.h`) or all includes; For now i've chosen all.
For reference, [milksnake's include filtering](https://github.com/getsentry/milksnake/blob/ef0723e41df23d8f6357570c69c1e69cb31f9e9e/milksnake/ffi.py#L8-L16).
=> Add no_includes option

src/bindgen/ir/structure.rs, tests/expectations/both/prefix.c, tests/expectations/prefix.c, tests/expectations/prefix.cpp, tests/expectations/tag/prefix.c, tests/rust/prefix.rs
We were incorrectly prefixing the tag (again in C mode, once in C++ mode).
=> Fix tagged enum's interactions with prefixing.

src/bindgen/ir/path.rs, tests/expectations/both/lifetime_arg.c, tests/expectations/lifetime_arg.c, tests/expectations/lifetime_arg.cpp, tests/expectations/tag/lifetime_arg.c, tests/rust/lifetime_arg.rs
The new test fails on master with `ERROR: Cannot use fn lifetime_arg::root ().`.
This matches the behavior of `cbindgen v3.3`. I'm not sure which version introduced the change.
=> Skip lifetime type args

src/bindgen/ir/enumeration.rs, src/bindgen/ir/function.rs, src/bindgen/ir/global.rs, src/bindgen/ir/structure.rs, src/bindgen/ir/ty.rs, src/bindgen/ir/typedef.rs, src/bindgen/ir/union.rs, src/bindgen/library.rs, src/bindgen/mangle.rs, src/bindgen/monomorph.rs, src/bindgen/parser.rs, tests/expectations/both/transform-op.c, tests/expectations/tag/transform-op.c, tests/expectations/transform-op.c, tests/expectations/transform-op.cpp, tests/rust/transform-op.rs, tests/rust/transform-op.toml
Going to need this if I ever aim to generate TransformOperation bindings and
remove a bunch of slow and ugly Gecko code:
https://searchfox.org/mozilla-central/rev/80ac71c1c54af788b32e851192dfd2de2ec18e18/servo/components/style/values/generics/transform.rs#189
With the caveat that I'll need to remove the options, but I can manage to do
that.
This also fixes a bunch of renaming bugs that I found while at it.
This patch has the gotcha that we need to remove the assertion of no-underscores
in mangled names... But I think it should be fine, and I'd rather not do a more
breaking change.
You can generate conflicting names in C using enum variants with the same name
as a struct regardless, for example, so I don't think this is terribly
important.
=> Add support for generic enums.

src/bindgen/ir/constant.rs, tests/expectations/both/prefixed_struct_literal.c, tests/expectations/both/prefixed_struct_literal_deep.c, tests/expectations/prefixed_struct_literal.c, tests/expectations/prefixed_struct_literal.cpp, tests/expectations/prefixed_struct_literal_deep.c, tests/expectations/prefixed_struct_literal_deep.cpp, tests/expectations/tag/prefixed_struct_literal.c, tests/expectations/tag/prefixed_struct_literal_deep.c, tests/rust/prefixed_struct_literal.rs, tests/rust/prefixed_struct_literal.toml, tests/rust/prefixed_struct_literal_deep.rs, tests/rust/prefixed_struct_literal_deep.toml
Fix #238
This ensures that constants of a struct type have their type and the
type of their underlying value expressions renamed in the case of a
prefix.
=> Propagate prefixes to struct literals

src/bindgen/ir/enumeration.rs, src/bindgen/rename.rs
A configuration such as
``` toml
[enum]
rename_variants = "ScreamingSnakeCase"
prefix_with_name = true
```
Should map an enum such `Foo::Bar` to `FOO_BAR` or `PREFIX_FOO_BAR` if there is a prefix set.
(I couldn't figure out how to move the former pr to this topic branch, sorry for the noise)
=> Fix prefixing + formatting for enums

src/bindgen/ir/documentation.rs
Documentation generated by cbindgen is not displayed in Doxygen's
output.
Solution: use comment styles supported by Doxygen
For C, this will be
```
/**
* ...
*/
```
For C++, this will be
```
///
/// ...
///
```
as described at http://www.stack.nl/~dimitri/doxygen/manual/docblocks.html
I've contemplating adding an option to cbindgen.toml for enabling this style but decided to go for a simpler route of making it the only style as it is still a valid comment and is not going to break anything. However, if it is better to put it behind a config flag, I'll gladly update this patch to do so.
=> Problem: Doxygen not picking up documentation

src/bindgen/cdecl.rs, tests/expectations/both/cdecl.c, tests/expectations/cdecl.c, tests/expectations/cdecl.cpp, tests/expectations/tag/cdecl.c
i.e. 'type I = *const [i32; 16]' should map to 'typedef const int32_t (*I)[16]'
instead of 'typedef int32_t (*I)[16]'
=> Properly propagate const into arrays.

src/bindgen/cdecl.rs, src/bindgen/ir/enumeration.rs, src/bindgen/ir/ty.rs, src/bindgen/mangle.rs, tests/expectations/annotation.cpp
This adds better support for references in the type system
and uses them for enumeration helpers instead of string
concatenation.
=> Support references better

src/bindgen/ir/enumeration.rs, tests/expectations/array.c, tests/expectations/array.cpp, tests/expectations/both/array.c, tests/expectations/tag/array.c, tests/rust/array.rs, tests/rust/array.toml
C++ arrays can't be assigned. We detect this situation and manually copy
over the elements.
=> Manually copy arrays

src/bindgen/ir/constant.rs, src/bindgen/parser.rs, tests/expectations/both/const_conflict.c, tests/expectations/both/transparent.c, tests/expectations/const_conflict.c, tests/expectations/const_conflict.cpp, tests/expectations/tag/const_conflict.c, tests/expectations/tag/transparent.c, tests/expectations/transparent.c, tests/expectations/transparent.cpp, tests/rust/transparent.rs
This attempts to fix `repr(transparent)` for associated constants by unwrapping the first field on structs (see https://github.com/eqrion/cbindgen/issues/238#issuecomment-435923997 for more context).
I didn't see obvious ways to infer whether the struct the `impl` block corresponds with is `repr(transparent)`, and the order isn't guaranteed (`impl` prior to `struct`). So we have to parse the struct declaration first, and reference it later, which is why the `impl` blocks are loaded after the regular loop now.
I'm not sure whether the general approach is correct, so any feedback is greatly appreciated, especially ideas to simplify the branching or remove the `Vec` allocation.
=> Remove member name from transparent associated constants

README.md, src/bindgen/config.rs, src/bindgen/ir/enumeration.rs, src/bindgen/ir/structure.rs, src/bindgen/ir/union.rs, src/bindgen/writer.rs, tests/expectations/body.c, tests/expectations/body.cpp, tests/expectations/both/body.c, tests/expectations/tag/body.c, tests/rust/body.rs, tests/rust/body.toml
This is useful to not make complex struct hard to use in C++ for example.
=> config: Allow to output user-defined stuff in the struct body.

src/bindgen/ir/ty.rs, src/bindgen/parser.rs, tests/expectations/both/style-crash.c, tests/expectations/style-crash.c, tests/expectations/style-crash.cpp, tests/expectations/tag/style-crash.c, tests/rust/style-crash.rs
This fixes a crash when running cbindgen 0.7.0 on the style crate.
=> parser: Properly skip associated constants on unsupported types. 

Cargo.lock, Cargo.toml, src/bindgen/utilities.rs
This bumps the minimum required `rustc` version to 1.32.
Updating `serde_derive` breaks the builds for `rustc < 1.32`.  See #203 for details.
```console
$ cargo +stable -vV
cargo 1.31.0 (339d9f9c8 2018-11-16)
release: 1.31.0
commit-hash: 339d9f9c8f400010df3282ae5582bf3a0f739004
commit-date: 2018-11-16
$ cargo +stable build
[...]
$ ldd target/debug/cbindgen
linux-vdso.so.1 (0x00007fff69b58000)
libproc_macro-eb9b1f5dc4b73ebd.so => not found
libsyntax-8b4b84ccec0d2e12.so => not found
libsyntax_pos-31f39647344993a7.so => not found
libstd-89cf9eb8d404bb7b.so => not found
libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f0d4a1a8000)
libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f0d4a18e000)
libc.so.6 => /usr/lib/libc.so.6 (0x00007f0d49fc8000)
/lib64/ld-linux-x86-64.so.2 => …
```
=> Unpin serde

src/bindgen/builder.rs, src/bindgen/config.rs, src/bindgen/parser.rs, tests/rust/associated_in_body.toml, tests/rust/bitflags.toml
Otherwise we may break code that does its own bitflags parsing.
In particular, this will prevent Gecko builds from breaking due to:
https://searchfox.org/mozilla-central/rev/92d11a33250a8e368c8ca3e962e15ca67117f765/gfx/webrender_bindings/webrender_ffi.h#67
(Which should go away once we start opting-in).
=> parser: Make bitflags expansion opt-in.

src/bindgen/bindings.rs, src/bindgen/config.rs, src/bindgen/ir/enumeration.rs, src/bindgen/ir/ty.rs, tests/expectations/asserted-cast.c, tests/expectations/asserted-cast.cpp, tests/expectations/both/asserted-cast.c, tests/expectations/both/transform-op.c, tests/expectations/tag/asserted-cast.c, tests/expectations/tag/transform-op.c, tests/expectations/transform-op.c, tests/expectations/transform-op.cpp, tests/rust/asserted-cast.rs, tests/rust/asserted-cast.toml, tests/rust/transform-op.rs, tests/rust/transform-op.toml
This fixes one of my pet-peeves. Without this patch, I need to add them manually
using the raw body stuff, or along the code that accesses the struct member,
none of those being ideal.
=> bindgen: Allow to auto-generate asserted casts for tagged enums.

README.md, src/bindgen/config.rs, tests/expectations/both/renaming-overrides-prefixing.c, tests/expectations/renaming-overrides-prefixing.c, tests/expectations/renaming-overrides-prefixing.cpp, tests/expectations/tag/renaming-overrides-prefixing.c, tests/rust/renaming-overrides-prefixing.rs, tests/rust/renaming-overrides-prefixing.toml
This is useful for opaque types or other types cbindgen doesn't otherwise understand.
=> config: Add an option to make explicit renaming override the prefix setting.

README.md, src/bindgen/config.rs, src/bindgen/ir/documentation.rs, tests/expectations/both/docstyle_c99.c, tests/expectations/docstyle_c99.c, tests/expectations/docstyle_c99.cpp, tests/expectations/tag/docstyle_c99.c, tests/rust/docstyle_c99.rs, tests/rust/docstyle_c99.toml
In modern C (post-C99) it's common to just use `// double-slash comments`, but currently cbindgen provides only `/* block-comment */` and `/// triple-slash comment` variants.
=> Add C99 doc comment style

src/bindgen/bitflags.rs, src/bindgen/parser.rs, tests/rust/assoc_const_conflict.rs, tests/rust/assoc_constant.rs, tests/rust/const_conflict.rs, tests/rust/const_transparent.rs, tests/rust/constant.rs, tests/rust/namespace_constant.rs, tests/rust/namespaces_constant.rs, tests/rust/prefix.rs, tests/rust/prefixed_struct_literal.rs, tests/rust/prefixed_struct_literal_deep.rs, tests/rust/rename.rs, tests/rust/struct_literal.rs
Fixes #123:
- Adds visibility check for module-level constants.
- Adds visibility check for associated constants.
- Fixes bitflags expansion to produce public associated constants (as the real expansion does).
Admittedly, because it's a long-standing issue, it's now a breaking change for users who started to rely on current behaviour :(
[![](https://imgs.xkcd.com/comics/workflow.png)](https://xkcd.com/1172/)
That said, I think this is a right change as current behaviour is not compliant with Rust visibility rules and produces lots of noise for unintentionally exported constants.
=> Respect visibility of constants

README.md, src/bindgen/config.rs, src/bindgen/ir/enumeration.rs, tests/expectations/both/destructor.c, tests/expectations/destructor.c, tests/expectations/destructor.cpp, tests/expectations/tag/destructor.c, tests/rust/destructor.rs, tests/rust/destructor.toml
This trades the ABI-safety (making the struct potentially unsafe to pass by
value), thus the opt-in rather than auto-generating it.
The TL;DR is that I need a way to share types that contain boxed slices from the
style system. That's fine when they're inside regular structs, since C++ does
the right thing, but for unions you need to make it explicit like this.
The actual Gecko setup will hook into the leak logging machinery to avoid silly
leaks and such of course.
=> ir: Add the possibility to auto-generate destructors of tagged unions.

src/bindgen/cargo/cargo.rs, src/bindgen/cargo/cargo_metadata.rs, src/bindgen/ir/cfg.rs, src/bindgen/parser.rs, tests/expectations/both/rename-crate.c, tests/expectations/rename-crate.c, tests/expectations/rename-crate.cpp, tests/expectations/tag/rename-crate.c, tests/rust/rename-crate/Cargo.lock, tests/rust/rename-crate/cbindgen.toml, tests/rust/rename-crate/no-extern/Cargo.lock, tests/rust/rename-crate/no-extern/Cargo.toml, tests/rust/rename-crate/no-extern/src/lib.rs, tests/rust/rename-crate/old-dep/Cargo.toml, tests/rust/rename-crate/old-dep/src/lib.rs, tests/rust/rename-crate/src/lib.rs
This changes our implementation to always ignore `extern crates`, favouring
collecting metadata from `cargo metadata` (the Cargo.toml) and `Cargo.lock`.
Future work might be needed to make this more robust.
Closes #331
=>  First implementation of Rust 2018 modules.

build.rs, tests/tests.rs
Still not great, I guess we should convert the tests to run the library version
of cbindgen, but this trivially-fixes #342.
=> Do a better job at detecting the final binary location.

README.md, docs.md
Need to flesh out the high level stuff but this brings the docs for the cbindgen.toml into a much more well-documented (and up to date) state.
Still working on this just posting it now since it's already ~3000 words so it'll take a long time to review if you want to actually do that.
=> Add comprehensive user docs

.travis.yml, Cargo.lock, Cargo.toml
This saves around 10 dependencies for people who uses `cbindgen` in the build.rs only (so they don't need clap)
=> Making clap an optional feature

docs.md, src/bindgen/builder.rs, src/bindgen/config.rs, src/bindgen/parser.rs, template.toml, tests/expectations/both/workspace.c, tests/expectations/both/workspace.compat.c, tests/expectations/tag/workspace.c, tests/expectations/tag/workspace.compat.c, tests/expectations/workspace.c, tests/expectations/workspace.compat.c, tests/expectations/workspace.cpp, tests/rust/workspace/cbindgen.toml, tests/rust/workspace/dep/src/lib.rs
This is a limitation that may not be useful if you're using it to parse known
dependencies.
=> Add an option to generate consts / globals / fn from parsed dependencies.

src/bindgen/ir/documentation.rs, src/bindgen/utilities.rs, tests/expectations/associated_in_body.c, tests/expectations/associated_in_body.compat.c, tests/expectations/associated_in_body.cpp, tests/expectations/bitflags.c, tests/expectations/bitflags.compat.c, tests/expectations/bitflags.cpp, tests/expectations/both/associated_in_body.c, tests/expectations/both/associated_in_body.compat.c, tests/expectations/both/bitflags.c, tests/expectations/both/bitflags.compat.c, tests/expectations/both/documentation.c, tests/expectations/both/documentation.compat.c, tests/expectations/documentation.c, tests/expectations/documentation.compat.c, tests/expectations/documentation.cpp, tests/expectations/tag/associated_in_body.c, tests/expectations/tag/associated_in_body.compat.c, tests/expectations/tag/bitflags.c, tests/expectations/tag/bitflags.compat.c, tests/expectations/tag/documentation.c, tests/expectations/tag/documentation.compat.c, tests/rust/documentation.rs
This required two changes in parallel.
As a first and obvious step it removes a check that skipped empty
lines during documentation loading, but it was also necessary to
refactor the `get_comment_lines()` utility method as a second step.
This second refactoring was necessary as each line in a doc comment
is trimmed and transformed in its own doc attribute. The attribute
of an empty line therefore contains an empty string as value. If we
now call `lines()` on such an empty string we end up with an empty
iterator as the method is internally configured to ignore trailing
empty lines.
fixes #369
--- 
Next to this I am unsure about the whole trimming logic inside `get_comment_lines()`. I can provide a second pull request to remove it, if wished. The reasoning would be that rust already removes …
=> Preserve empty lines in doc comments.

src/bindgen/cargo/cargo_expand.rs, src/bindgen/parser.rs
With the current version of cbindgen it's not possible to have macros in the crate cbindgen is triggered from if you run cbindgen programmatically via build.rs. This issue was reported as #347. This PR fixes that problem.
I've create two commits as it is kind of two issues that need a fix.
When crates should get expanded, then cargo is run again from within cbindgen.
When cbindgen is started from a build.rs file, this means that cargo is starting
another cargo run.
Cargo locks the directory it is running on. If two cargos spawn by each other
run with the same target directory, then they both want to accquire a lock and
hence deadlock.
This commit fixes the problem with running the spawned cargo at a different
directory. Please note that this will always be the same directory, hence
any …
=> Make running cbindgen with own create expansion from build.rs

src/bindgen/ir/annotation.rs, src/bindgen/ir/documentation.rs, src/bindgen/utilities.rs, tests/expectations/both/documentation.c, tests/expectations/both/documentation.compat.c, tests/expectations/documentation.c, tests/expectations/documentation.compat.c, tests/expectations/documentation.cpp, tests/expectations/tag/documentation.c, tests/expectations/tag/documentation.compat.c, tests/rust/documentation.rs
This fixes two additional documentation related issues: #184 & #374. Both effect nearly the same parts of the source code. It also updates the `documentation` test to verify the new expected behavior.
---
Feel free to nitpick. I will try to come up with all required changes to get this merged.
=> Avoid most trimming and preserve comment structure.

src/bindgen/cargo/cargo_expand.rs
This helps investigating the mysterious errors that sometimes appear, like https://github.com/servo/media/issues/280#issuecomment-509338508
=> Enable verbose logging as well as echo the command line on expansion.

docs.md, src/bindgen/config.rs, src/bindgen/ir/enumeration.rs, template.toml, tests/expectations/both/destructor-and-copy-ctor.c, tests/expectations/both/destructor-and-copy-ctor.compat.c, tests/expectations/destructor-and-copy-ctor.c, tests/expectations/destructor-and-copy-ctor.compat.c, tests/expectations/destructor-and-copy-ctor.cpp, tests/expectations/tag/destructor-and-copy-ctor.c, tests/expectations/tag/destructor-and-copy-ctor.compat.c, tests/rust/destructor-and-copy-ctor.rs, tests/rust/destructor-and-copy-ctor.toml
This allows to clean up a pattern that has been showing up lately, see
occurrences of:
https://searchfox.org/mozilla-central/rev/9775cca0a10a9b5c5f4e15c8f7b3eff5bf91bbd0/servo/ports/geckolib/cbindgen.toml#329
=> ir: Add an option to generate an empty, default constructor for tagged enums.

docs.md
=> remove unnecesary "`" from docs.md

src/bindgen/bindings.rs, tests/expectations/both/namespace_constant.compat.c, tests/expectations/both/namespaces_constant.compat.c, tests/expectations/both/using_namespaces.compat.c, tests/expectations/namespace_constant.compat.c, tests/expectations/namespaces_constant.compat.c, tests/expectations/tag/namespace_constant.compat.c, tests/expectations/tag/namespaces_constant.compat.c, tests/expectations/tag/using_namespaces.compat.c, tests/expectations/using_namespaces.compat.c
This implements #391 
Ideally I think some of the outputs should be refactored into seperate functions e.g. `open_cpp_compat` and `close_cpp_compat` to keep things DRY.
=> Surround namespace with __cplusplus ifdef in cpp_compat mode

src/bindgen/bindings.rs, src/bindgen/ir/constant.rs, tests/expectations/associated_in_body.cpp, tests/expectations/bitflags.cpp, tests/expectations/both/struct_literal_order.c, tests/expectations/both/struct_literal_order.compat.c, tests/expectations/prefixed_struct_literal.cpp, tests/expectations/prefixed_struct_literal_deep.cpp, tests/expectations/struct_literal.cpp, tests/expectations/struct_literal_order.c, tests/expectations/struct_literal_order.compat.c, tests/expectations/struct_literal_order.cpp, tests/expectations/tag/struct_literal_order.c, tests/expectations/tag/struct_literal_order.compat.c, tests/rust/struct_literal_order.rs
fix #397 
- Use list-initializer for C++ struct
- Sort struct literal elements by struct definition order
=> Initialize struct literal with list-initializer for C++11 standard

docs.md, src/bindgen/config.rs, src/bindgen/ir/enumeration.rs, tests/expectations/destructor-and-copy-ctor.cpp, tests/rust/destructor-and-copy-ctor.rs, tests/rust/destructor-and-copy-ctor.toml
And recommend its usage if copy-constructors are being generated, as otherwise
C++ in its whole glory would do a bitwise copy, which is not really what you
want if you have constructors / destructors around.
=> enum: Add an option to generate copy-assignments.

src/bindgen/ir/enumeration.rs, src/bindgen/ir/repr.rs, tests/expectations/both/enum.c, tests/expectations/both/enum.compat.c, tests/expectations/enum.c, tests/expectations/enum.compat.c, tests/expectations/enum.cpp, tests/expectations/tag/enum.c, tests/expectations/tag/enum.compat.c, tests/rust/enum.rs
Since there is a native C type for 64-bit integers (*int64_t), we can
just add support for them. Support for larger enums (u128) are currently
unstable and don't have a reasonable (standard-enough) C representation
to support at the moment.
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>
=> ir: support #[repr(*64)] enums

docs.md, src/bindgen/config.rs, src/bindgen/ir/enumeration.rs, template.toml, tests/expectations/both/enum.c, tests/expectations/both/enum.compat.c, tests/expectations/enum.c, tests/expectations/enum.compat.c, tests/expectations/enum.cpp, tests/expectations/tag/enum.c, tests/expectations/tag/enum.compat.c, tests/rust/enum.rs
This option allows specifying that a C++ enum should be emitted with plain `enum` rather than `enum class`. It's true that `enum class` should generally be preferred, but sometimes there's existing code which is already using plain `enum`, and porting that code to Rust becomes easier when `cbindgen` can emit plain `enum`.
This option can be overridden on a per-enum basis using a `cbindgen:` annotation.
It defaults to true for two reasons:
* Backward compatibility.
* `enum class` is probably actually what you want, in general.
=> Add enum_class option

src/bindgen/parser.rs, src/bindgen/utilities.rs, tests/expectations/both/export_name.c, tests/expectations/both/export_name.compat.c, tests/expectations/export_name.c, tests/expectations/export_name.compat.c, tests/expectations/export_name.cpp, tests/expectations/tag/export_name.c, tests/expectations/tag/export_name.compat.c, tests/rust/export_name.rs
Fixes #283 
Added a helper trait / methods on `syn::ItemFn` to handle attribute lookup, including:
- `export_name_attr` to lookup the attribute
- `exported_name` to select the correct name (`export_name` if it was set, otherwise the function name if it's `no_mangle`, otherwise `None`)
- `attr_name_value_lookup` added to `SynAttributeHelpers` to factor out attribute lookup
=> Add support for the export_name function attribute

docs.md, src/bindgen/config.rs, src/bindgen/ir/enumeration.rs, src/bindgen/ir/structure.rs, src/bindgen/ir/union.rs, src/bindgen/writer.rs, tests/expectations/body.c, tests/expectations/body.compat.c, tests/expectations/body.cpp, tests/expectations/both/body.c, tests/expectations/both/body.compat.c, tests/expectations/tag/body.c, tests/expectations/tag/body.compat.c, tests/rust/body.rs, tests/rust/body.toml
This change allows users to prepend text to the body of structs etc. Previously, users could only append, and this change allows both.
While working on this, I noticed that appending for untagged enums doesn't seem to work:
It's in the test toml file:
```
"MyCLikeEnum" = """
BogusVariantForSerializationForExample,
"""
```
But I looked through the history and `BogusVariantForSerializationForExample` has never appeared in any of the expected outputs. If this is a bug, I can open another pull request to fix it.
Fixes #448
=> Add [export.body_prepend] to config

src/bindgen/utilities.rs, tests/expectations/both/documentation_attr.c, tests/expectations/both/documentation_attr.compat.c, tests/expectations/documentation_attr.c, tests/expectations/documentation_attr.compat.c, tests/expectations/documentation_attr.cpp, tests/expectations/tag/documentation_attr.c, tests/expectations/tag/documentation_attr.compat.c, tests/rust/documentation_attr.rs
This should fix #442
Please tell me if there anything I can do better :)
=> Handle new line in doc attribute

src/bindgen/ir/constant.rs, tests/expectations/both/constant.c, tests/expectations/both/constant.compat.c, tests/expectations/both/prefix.c, tests/expectations/both/prefix.compat.c, tests/expectations/constant.c, tests/expectations/constant.compat.c, tests/expectations/constant.cpp, tests/expectations/prefix.c, tests/expectations/prefix.compat.c, tests/expectations/prefix.cpp, tests/expectations/tag/constant.c, tests/expectations/tag/constant.compat.c, tests/expectations/tag/prefix.c, tests/expectations/tag/prefix.compat.c, tests/rust/prefix.rs, tests/tests.rs
This PR enables `-Wall -Werror -Wno-attributes` when compiling C++ and C. With these warnings in place, several warnings are generated.
```
/cbindgen/tests/expectations/constant.cpp:8:31: error: character constant too long for its type [-Werror]
8 | static const uint32_t EQUID = L'\u10083';
|                               ^~~~~~~~~~
cc1plus: all warnings being treated as errors
```
This is fixed by replacing the `L'\u10083'` syntax with `L'\U00010083'`. The `U` variant supports 8 digits, while `\u` only supports 4.
```
/cbindgen/tests/expectations/associated_in_body.cpp:45:1: error: inline variables are only available with ‘-std=c++17’ or ‘-std=gnu++17’ [-Werror]
45 | inline const StyleAlignFlags StyleAlignFlags::AUTO = StyleAlignFlags{ /* .bits = */ 0 };
| ^~~~~~ …
```
=> Enable most warnings, and fix findings.

src/bindgen/ir/documentation.rs, src/bindgen/ir/enumeration.rs, src/bindgen/parser.rs, tests/expectations/both/sentinel.c, tests/expectations/both/sentinel.compat.c, tests/expectations/sentinel.c, tests/expectations/sentinel.compat.c, tests/expectations/sentinel.cpp, tests/expectations/tag/sentinel.c, tests/expectations/tag/sentinel.compat.c, tests/rust/sentinel.rs, tests/rust/sentinel.toml
Like enum.prefix_with_name, or documentation style.
Fixes https://github.com/eqrion/cbindgen/issues/458
=> Make sentinel variant respect regular config

tests/testing-helpers.h, tests/tests.rs
This will be useful to add static assertion to some tests like #463 wants to do.
For example, in the case of the test for #463, the test would need something
like:
trailer = """
#include <assert.h>
#if defined(CBINDGEN_STYLE_TAG) && !defined(__cplusplus)
static_assert(sizeof(struct P) == 4, "unexpected size for P");
#else
static_assert(sizeof(P) == 4, "unexpected size for P");
#endif
"""
As more of these tests are added it may be worth just adding a helper header
like this to avoid some duplication:
#include <assert.h>
#if defined(CBINDGEN_STYLE_TAG) && !defined(__cplusplus)
#define CBINDGEN_STRUCT(name) struct name
#else
#define CBINDGEN_STRUCT(name) name
#endif
And so on, so the previous configuration would become just:
trailer = """
#include "testing-helpers.h" // Or whatever …
=> tests: Provide style definition to the C / C++ tests.

src/bindgen/ir/constant.rs, tests/expectations/associated_in_body.c, tests/expectations/associated_in_body.compat.c, tests/expectations/associated_in_body.cpp, tests/expectations/bitflags.c, tests/expectations/bitflags.compat.c, tests/expectations/bitflags.cpp, tests/expectations/both/associated_in_body.c, tests/expectations/both/associated_in_body.compat.c, tests/expectations/both/bitflags.c, tests/expectations/both/bitflags.compat.c, tests/expectations/both/constant.c, tests/expectations/both/constant.compat.c, tests/expectations/constant.c, tests/expectations/constant.compat.c, tests/expectations/constant.cpp, tests/expectations/tag/associated_in_body.c, tests/expectations/tag/associated_in_body.compat.c, tests/expectations/tag/bitflags.c, tests/expectations/tag/bitflags.compat.c, tests/expectations/tag/constant.c, tests/expectations/tag/constant.compat.c, tests/rust/constant.rs
=> Emit documentation on constants

src/bindgen/cdecl.rs, src/bindgen/ir/ty.rs, tests/expectations/both/cdecl.c, tests/expectations/both/cdecl.compat.c, tests/expectations/both/fns.c, tests/expectations/both/fns.compat.c, tests/expectations/both/simplify-option-ptr.c, tests/expectations/both/simplify-option-ptr.compat.c, tests/expectations/cdecl.c, tests/expectations/cdecl.compat.c, tests/expectations/fns.c, tests/expectations/fns.compat.c, tests/expectations/fns.cpp, tests/expectations/simplify-option-ptr.c, tests/expectations/simplify-option-ptr.compat.c, tests/expectations/simplify-option-ptr.cpp, tests/expectations/tag/cdecl.c, tests/expectations/tag/cdecl.compat.c, tests/expectations/tag/fns.c, tests/expectations/tag/fns.compat.c, tests/expectations/tag/simplify-option-ptr.c, tests/expectations/tag/simplify-option-ptr.compat.c
Fix #470 
This `void` in some C++ files should be fine according to standard ([ref][stackoverflow ref])
Let's me know if there's anything I can improve :)
[stackoverflow ref]: https://softwareengineering.stackexchange.com/a/287002
=> bindgen: enable "void prototype" while writing struct field

src/bindgen/ir/enumeration.rs
This fixes C++ -Wcovered-switch-default warnings.
=> Only write `default` cases if the switch is not exhaustive.

src/bindgen/parser.rs
fix #467
I'd like to hear your opinion about my implementation.
- are these warning messages okay in each case?
- is the "match in if-else statement" okay? or should I write it in a single match statement?
Please let me know what's the suitable way to go :)
=> Omit or display more detailed warning message while trying to generate declaration from Rust functions

tests/tests.rs
This is needed when running tests with clang/clang++, as some of the tests have
errors that clang reports which gcc does not such as unused static const
variables.
=> Check for CFLAGS and CXXFLAGS when running tests

src/bindgen/ir/global.rs, tests/expectations/both/global_variable.c, tests/expectations/both/global_variable.compat.c, tests/expectations/global_variable.c, tests/expectations/global_variable.compat.c, tests/expectations/global_variable.cpp, tests/expectations/tag/global_variable.c, tests/expectations/tag/global_variable.compat.c, tests/rust/global_variable.rs
fix #476 
Just wondering, should I use `Source::write of (String, Type)` or `cdecl::write_field` directly?
=> ir: write declaration of global variable like struct fields

src/bindgen/ir/ty.rs, src/bindgen/parser.rs, tests/expectations/both/cell.c, tests/expectations/both/cell.compat.c, tests/expectations/cell.c, tests/expectations/cell.compat.c, tests/expectations/cell.cpp, tests/expectations/tag/cell.c, tests/expectations/tag/cell.compat.c, tests/rust/cell.rs
RefCell is opaque. Cell is repr(transparent) so can just be the inner type.
Simplify it the same way as we simplify Option<&mut T> and such.
Fixes #488
=> ir: Add support for Cell and RefCell.

src/bindgen/ir/enumeration.rs, tests/expectations/both/reserved.c, tests/expectations/both/reserved.compat.c, tests/expectations/reserved.c, tests/expectations/reserved.compat.c, tests/expectations/reserved.cpp, tests/expectations/tag/reserved.c, tests/expectations/tag/reserved.compat.c, tests/rust/reserved.rs
Should fix  #368
I escape the `enum Tag` as well since they are quite relevant.
=> Escape type name and field name of generated tagged union

src/bindgen/parser.rs, tests/expectations/associated_constant_panic.c, tests/expectations/associated_constant_panic.compat.c, tests/expectations/associated_constant_panic.cpp, tests/expectations/both/associated_constant_panic.c, tests/expectations/both/associated_constant_panic.compat.c, tests/expectations/tag/associated_constant_panic.c, tests/expectations/tag/associated_constant_panic.compat.c, tests/rust/associated_constant_panic.rs
We don't handle it, but no reason to panic.
=> parser: Don't panic when finding associated constants to a primitive.

src/bindgen/library.rs, tests/expectations/both/exclude_generic_monomorph.c, tests/expectations/both/exclude_generic_monomorph.compat.c, tests/expectations/exclude_generic_monomorph.c, tests/expectations/exclude_generic_monomorph.compat.c, tests/expectations/exclude_generic_monomorph.cpp, tests/expectations/tag/exclude_generic_monomorph.c, tests/expectations/tag/exclude_generic_monomorph.compat.c, tests/rust/exclude_generic_monomorph.rs, tests/rust/exclude_generic_monomorph.toml
=> Allow excluding monomorph structs in C mode.

src/bindgen/ir/enumeration.rs, tests/expectations/cfg.cpp, tests/expectations/derive-eq.cpp
This fixes: https://bugzilla.mozilla.org/show_bug.cgi?id=1628754#c7
=> enum: Unconditionally generate a return statement in partialeq implementations.

Cargo.lock, Cargo.toml, src/bindgen/ir/enumeration.rs, src/bindgen/ir/function.rs, src/bindgen/ir/structure.rs, src/bindgen/ir/union.rs, src/bindgen/parser.rs, src/bindgen/rename.rs
All case conversion cases seem to be covered by this crate so this greatly simplifies `rename.rs`.
=> Fix #418: Use heck for case conversion

docs.md, src/bindgen/bindings.rs, src/bindgen/builder.rs, src/bindgen/config.rs, template.toml, tests/expectations/both/raw_lines.c, tests/expectations/both/raw_lines.compat.c, tests/expectations/raw_lines.c, tests/expectations/raw_lines.compat.c, tests/expectations/raw_lines.cpp, tests/expectations/tag/raw_lines.c, tests/expectations/tag/raw_lines.compat.c, tests/rust/raw_lines.rs, tests/rust/raw_lines.toml
Let the user add raw C code in the generated header after the include
blocks.
It matches what bindgen provides.
=> Add support for after_includes

docs.md, src/bindgen/parser.rs, src/bindgen/utilities.rs, tests/expectations/both/ignore.c, tests/expectations/both/ignore.compat.c, tests/expectations/ignore.c, tests/expectations/ignore.compat.c, tests/expectations/ignore.cpp, tests/expectations/tag/ignore.c, tests/expectations/tag/ignore.compat.c, tests/rust/ignore.rs
As a custom annotation like the others.
Fixes #518 and cleans up a bunch of the related code while at it.
=> Add support for ignoring parsing of top-level items.

README.md, docs.md
The default instructions produce C++ headers that are incompatible with
C.  This makes it explicit what the default command does, and the switch
needed to produce C headers.
Fixes #393.
=> Add instructions for C language switch

src/bindgen/bindings.rs, src/bindgen/ir/constant.rs, tests/expectations/both/constant.c, tests/expectations/both/constant.compat.c, tests/expectations/both/rename.c, tests/expectations/both/rename.compat.c, tests/expectations/constant.c, tests/expectations/constant.compat.c, tests/expectations/constant.cpp, tests/expectations/rename.c, tests/expectations/rename.compat.c, tests/expectations/rename.cpp, tests/expectations/tag/constant.c, tests/expectations/tag/constant.compat.c, tests/expectations/tag/rename.c, tests/expectations/tag/rename.compat.c, tests/rust/constant.rs, tests/rust/rename.rs
=> Support casts in constants

src/bindgen/config.rs, src/bindgen/ir/function.rs, tests/expectations/both/fns.c, tests/expectations/both/fns.compat.c, tests/expectations/both/function_noreturn.c, tests/expectations/both/function_noreturn.compat.c, tests/expectations/fns.c, tests/expectations/fns.compat.c, tests/expectations/fns.cpp, tests/expectations/function_noreturn.c, tests/expectations/function_noreturn.compat.c, tests/expectations/function_noreturn.cpp, tests/expectations/tag/fns.c, tests/expectations/tag/fns.compat.c, tests/expectations/tag/function_noreturn.c, tests/expectations/tag/function_noreturn.compat.c, tests/rust/fns.rs, tests/rust/function_noreturn.rs, tests/rust/function_noreturn.toml
This is my attempt to add support for "never" return type in function declarations.
Solves #548
=> Support "never" return type

src/bindgen/cdecl.rs, src/bindgen/ir/function.rs, tests/expectations/both/function_args.c, tests/expectations/both/function_args.compat.c, tests/expectations/both/swift_name.c, tests/expectations/both/swift_name.compat.c, tests/expectations/function_args.c, tests/expectations/function_args.compat.c, tests/expectations/function_args.cpp, tests/expectations/swift_name.c, tests/expectations/swift_name.compat.c, tests/expectations/swift_name.cpp, tests/expectations/tag/function_args.c, tests/expectations/tag/function_args.compat.c, tests/expectations/tag/swift_name.c, tests/expectations/tag/swift_name.compat.c, tests/rust/function_args.rs, tests/rust/swift_name.rs
We don't support unnamed arguments, and we give a terrible error
("Parameter has an unsupported type.") when you use them.
They're very simple to implement so we should just do it.
=> function: Add support for wildcards in arguments.

docs.md, src/bindgen/cdecl.rs, src/bindgen/config.rs, src/bindgen/ir/constant.rs, src/bindgen/ir/function.rs, src/bindgen/ir/global.rs, src/bindgen/ir/ty.rs, src/bindgen/mangle.rs, tests/expectations/both/nonnull_attribute.c, tests/expectations/both/nonnull_attribute.compat.c, tests/expectations/nonnull_attribute.c, tests/expectations/nonnull_attribute.compat.c, tests/expectations/nonnull_attribute.cpp, tests/expectations/tag/nonnull_attribute.c, tests/expectations/tag/nonnull_attribute.compat.c, tests/rust/nonnull_attribute.rs, tests/rust/nonnull_attribute.toml
This allows clang and swiftc users to use `_Nonnull`
Tested with `CC=clang CXX=clang++ cargo test` as well as `cargo test`
=> Add support for an optional nonnull attribute

src/bindgen/ir/generic_path.rs, src/bindgen/ir/opaque.rs, src/bindgen/parser.rs, tests/expectations/both/opaque.c, tests/expectations/both/opaque.compat.c, tests/expectations/cell.cpp, tests/expectations/monomorph-1.cpp, tests/expectations/monomorph-3.cpp, tests/expectations/opaque.c, tests/expectations/opaque.compat.c, tests/expectations/opaque.cpp, tests/expectations/std_lib.cpp, tests/expectations/swift_name.cpp, tests/expectations/tag/opaque.c, tests/expectations/tag/opaque.compat.c, tests/rust/opaque.rs, tests/rust/opaque.toml
There are two situations where we can legitimately end up with a
different number of template params.
Fixes #532.
Fixes #527.
=> ir: Be less strict when instantiating opaque types.

src/bindgen/config.rs, src/bindgen/ir/enumeration.rs, src/bindgen/ir/opaque.rs, src/bindgen/ir/structure.rs, src/bindgen/ir/typedef.rs, src/bindgen/ir/union.rs, src/bindgen/library.rs, src/bindgen/mangle.rs
Addresses #437 
I'm not sure if `mangling_separator` should live in ExportConfig or elsewhere. 
Also wondering if there is a neater way to pass `mangling_separator` down the call chain.
Tested with a `cpp_compat` config, without the new option and with. 
Not able to run tests yet due to #499
=> Add option for `mangling_separator` in ExportConfig

src/bindgen/config.rs, src/bindgen/writer.rs, template.toml, tests/expectations/both/linestyle_cr.c, tests/expectations/both/linestyle_cr.compat.c, tests/expectations/both/linestyle_crlf.c, tests/expectations/both/linestyle_crlf.compat.c, tests/expectations/both/linestyle_lf.c, tests/expectations/both/linestyle_lf.compat.c, tests/expectations/linestyle_cr.c, tests/expectations/linestyle_cr.compat.c, tests/expectations/linestyle_cr.cpp, tests/expectations/linestyle_crlf.c, tests/expectations/linestyle_crlf.compat.c, tests/expectations/linestyle_crlf.cpp, tests/expectations/linestyle_lf.c, tests/expectations/linestyle_lf.compat.c, tests/expectations/linestyle_lf.cpp, tests/expectations/tag/linestyle_cr.c, tests/expectations/tag/linestyle_cr.compat.c, tests/expectations/tag/linestyle_crlf.c, tests/expectations/tag/linestyle_crlf.compat.c, tests/expectations/tag/linestyle_lf.c, tests/expectations/tag/linestyle_lf.compat.c, tests/rust/linestyle_cr.rs, tests/rust/linestyle_cr.toml, tests/rust/linestyle_crlf.rs, tests/rust/linestyle_crlf.toml, tests/rust/linestyle_lf.rs, tests/rust/linestyle_lf.toml
Hello!
This is a PR to allow specification of the desired line ending style in the generated file. The background for this is working in a git repository shared between Windows and Linux users. The windows users have their git `core.autocrlf` flag setup to check out CRLF, submit LF, and Linux users only work with LF. Both the input and output files are tracked in source control to highlight inadvertent changes in the generated API. 
Since cbindgen generates with only '\n' (based on `write!`) their checked-out CRLF header file becomes LF, and they both get a meaningless whitespace-only diff as-well-as a warning from git that they have a LF file in their CRLF repository.
This changeset introduces a new configuration option that gives four options for line endings: LF, CR, CRLF, or Native. …
=> Add support for specifying line ending style

src/bindgen/config.rs, src/bindgen/ir/enumeration.rs, src/bindgen/ir/function.rs, src/bindgen/ir/structure.rs, src/bindgen/ir/union.rs, src/bindgen/mangle.rs, src/bindgen/rename.rs, src/bindgen/utilities.rs, tests/expectations/annotation.cpp, tests/expectations/array.cpp, tests/expectations/asserted-cast.cpp, tests/expectations/cfg.cpp, tests/expectations/destructor-and-copy-ctor.cpp, tests/expectations/transform-op.cpp
Option<RenameRule> doesn't make sense anywhere because there's a
RenameRule::None itself, which is also default.
This simplifies a bit the rename rules code, and removes one weird
"default-to-gecko-case" that seems snuck by.
This is a breaking change because the `config` types are exposed
publicly, but #575 is a breaking-change as well so let's take
advantage of the opportunity.
=> Refactor rename-rules to make more sense.

src/bindgen/ir/constant.rs, tests/expectations/both/constant_user_defined_type.c, tests/expectations/both/constant_user_defined_type.compat.c, tests/expectations/constant_user_defined_type.c, tests/expectations/constant_user_defined_type.compat.c, tests/expectations/constant_user_defined_type.cpp, tests/expectations/tag/constant_user_defined_type.c, tests/expectations/tag/constant_user_defined_type.compat.c, tests/rust/constant_user_defined_type.rs
(Take 1 - https://github.com/eqrion/cbindgen/pull/588.)
When converting `const` items stop checking their types and check only values instead.
As long as we can convert the right hand side with `Literal::load` we assume that we can convert the left hand side as well, perhaps using user-defined types defined in the crate.
The one exception is `str` type.
Despite being able to convert string literals with `Literal::load`, we cannot convert `str`.
We can't even introduce an opaque type for it because it's unsized and pointers to it are fat.
So we just remove the support for string literals from `Literal::load`, processing of `const` items is the only place where it is used anyway.
Closes https://github.com/eqrion/cbindgen/issues/583
=> Support constants with arbitrary types (take 2)

src/bindgen/builder.rs
It's impossible to select desired style when `cbindgen` is configured from the build script. This PR adds the missing function.
I happen to notice that none of the tests even try to create a `Builder` object, so I wasn't sure what style of tests is preferable here. I've created a trivial one just to hit newly added lines, please let me know if it has to be changed to some other format.
=> Add missing function `with_style` to the Builder

.github/workflows/cbindgen.yml
There's no clippy check forcing new features now (fbdad17dc630bd2e0cf7975c879a6738e3949074), so the minimum supported Rust version is currently enforced by dependencies (`remove_dir_all-0.5.3`) and should be relatively stable.
Should it be checked on CI to avoid bumping the version requirements accidentally?
=> CI: Add a minimum Rust version check?

docs.md, src/bindgen/bindings.rs, src/bindgen/cdecl.rs, src/bindgen/config.rs, src/bindgen/ir/enumeration.rs, src/bindgen/ir/repr.rs, src/bindgen/ir/ty.rs, template.toml, tests/expectations/size-types.c, tests/expectations/size-types.compat.c, tests/expectations/size-types.cpp, tests/rust/size-types.rs, tests/rust/size-types.toml
This PR adds a new global option `usize_is_size_t` that mirrors `size_t_is_usize` in bindgen and allows to map `usize`/`isize` into the more traditional pair `size_t`/`ptrdiff_t` instead of `uintptr_t`/`intptr_t` into which they are converted currently.
(I'd personally want to see this as the default, similarly to https://github.com/rust-lang/rust-bindgen/pull/1902, but I didn't change any defaults in this PR.)
cc https://github.com/eqrion/cbindgen/issues/239
=> Add an option for converting usize/isize into size_t/ptrdiff_t

src/bindgen/ir/constant.rs, src/bindgen/ir/enumeration.rs, tests/expectations/enum_discriminant.c, tests/expectations/enum_discriminant.compat.c, tests/expectations/enum_discriminant.cpp, tests/rust/enum_discriminant.rs
```rust
enum E {
V = EXPR
}
```
now supports the same set of expressions as
```
const C: Type = EXPR;
```
with paths and binary operators probably being the most important case in practice
```
enum E {
V = CONST,
U = CONST + 1,
}
```
=> Support wider range of expressions in enum discriminants

docs.md, src/bindgen/bindings.rs, src/bindgen/config.rs, src/bindgen/ir/enumeration.rs
Extracted from https://github.com/eqrion/cbindgen/pull/590.
Many config options only make sense when some other options have specific values (e.g. the language is C, or something like that) and should return "false" or "empty list" otherwise, as they were not set at all.
https://github.com/eqrion/cbindgen/pull/590 is going to introduce more such getters, but a getter from `cpp_compat` makes sense regardless of Cython.
`cpp_compat` should be considered `true` only if the current language is C, otherwise it should be considered effectively `false` even if set. This PR introduces a method `Config::cpp_compatible_c` to solve this problem.
I didn't rename the original field `cpp_compat` because it's a part of the public crate interface, but ideally it would be renamed to something like …
=> Use a getter for accessing `Config::cpp_compat`

docs.md, src/bindgen/bindings.rs, src/bindgen/config.rs, tests/expectations/cython_options.compat.c, tests/expectations/cython_options.cpp, tests/expectations/cython_options.pyx, tests/expectations/cython_options.tag.pyx, tests/rust/cython_options.toml
C header `.h` and Cython `.pxd` are generated as a pair, so it's important to be able to generate them from a single config file.
Two new options in this PR allow to do it without hacks.
One option allows to "link" the `.pxd` to `.h`, and another one allows to add some imports.
(I don't plan to add any more Cython-specific options in the near future, these two are the ones with highest return-on-investment.)
=> cython: Add options for specifying header and imports

src/bindgen/config.rs, src/bindgen/ir/enumeration.rs
Fixes the CI failure on master - https://github.com/eqrion/cbindgen/runs/1454777165.
Also add comments for https://github.com/eqrion/cbindgen/pull/620#discussion_r526255315
UPD: Looks like other `HashMap`s in config are used for search rather than for output, so they don't introduce this kind of randomness.
=> cython: Fix a non-reproducible test

tests/profile.rs
=> tests: Provide a fallback for CARGO_BIN_EXE_ for earlier Rusts

src/bindgen/ir/enumeration.rs, src/bindgen/ir/structure.rs, tests/expectations/must_use.both.c, tests/expectations/must_use.both.compat.c, tests/expectations/must_use.c, tests/expectations/must_use.compat.c, tests/expectations/must_use.tag.c, tests/expectations/must_use.tag.compat.c
Break up enormous `Enum::write` into several smaller functions, add comments, try to avoid some naming ambiguities.
(Also `must_use` annotations for enums are now added in C mode and not only in C++ code, because they both use common `fn open_struct_or_union` logic now.)
(It's better to review this with whitespace changes ignored.)
This is a preparation for fixing https://github.com/eqrion/cbindgen/issues/353.
=> Refactor `Enum::write`

src/bindgen/parser.rs, tests/expectations/mod_2018.both.c, tests/expectations/mod_2018.both.compat.c, tests/expectations/mod_2018.c, tests/expectations/mod_2018.compat.c, tests/expectations/mod_2018.cpp, tests/expectations/mod_2018.pyx, tests/expectations/mod_2018.tag.c, tests/expectations/mod_2018.tag.compat.c, tests/expectations/mod_2018.tag.pyx, tests/rust/mod_2018/src/nested.rs, tests/rust/mod_2018/src/other2.rs
We need the current mod dir to resolve #[path], not the one we get for
rust 2018.
Fixes #599
=> parser: Fix resolution of #[path] dependencies from certain modules.

src/bindgen/ir/enumeration.rs, tests/expectations/enum_discriminant.c, tests/expectations/enum_discriminant.compat.c, tests/expectations/enum_discriminant.cpp, tests/expectations/enum_discriminant.pyx, tests/rust/enum_discriminant.toml
A missing piece of https://github.com/eqrion/cbindgen/pull/614.
=> enum: Do not forget to rename entities in enum discriminants

src/bindgen/ir/enumeration.rs, src/bindgen/ir/field.rs, src/bindgen/ir/structure.rs, src/bindgen/ir/union.rs, tests/expectations/cfg.both.c, tests/expectations/cfg.both.compat.c, tests/expectations/cfg.c, tests/expectations/cfg.compat.c, tests/expectations/cfg.cpp, tests/expectations/cfg.pyx, tests/expectations/cfg.tag.c, tests/expectations/cfg.tag.compat.c, tests/expectations/cfg.tag.pyx, tests/rust/cfg.rs
Rebase of https://github.com/eqrion/cbindgen/pull/316.
- The ugly (but apparently harmless) stray semicolon
```c++
#if !defined(FOO)
uint8_t field
#endif
;
```
- Deriving C++ methods on structs with conditional fields is not supported.
Both issues should be resolved by supporting configuring individual list elements in `write_vertical_source_list`, but that's a separate task.
=> Partially support `#[cfg]`s on fields

.github/workflows/cbindgen.yml, Cargo.toml
As it relies in a sub-crate, see rust-lang/cargo#9017.
=> Skip profiles test in package.

src/bindgen/parser.rs
This applies the 'TODO' at line 99 in `src/bindgen/parser.rs`
The `Parser::should_parse_dependency` method should now be able to take a `&str` argument.
This function is only called in one place (line 165 in `src/bindgen/parser.rs`), so it should not introduce an unexpected issue (and all tests pass anyway :slightly_smiling_face:)
=> should_parse_dependency &str arg

src/bindgen/builder.rs
Added missing function to builder:
see issue: Add parse extra bindings to builder #644
=> [#644] Add parse extra bindings to builder

.clippy.toml, .github/workflows/cbindgen.yml, src/bindgen/cargo/cargo_expand.rs, src/bindgen/ir/enumeration.rs, src/bindgen/ir/function.rs, src/bindgen/ir/structure.rs
Now it is possible to set the minimal `Rust` version in the `.clippy.toml` file, so lints newer than `MSRV` are disabled.
=> Reintroduce clippy checks

src/bindgen/declarationtyperesolver.rs, src/bindgen/ir/enumeration.rs, src/bindgen/ir/structure.rs, src/bindgen/ir/typedef.rs, src/bindgen/library.rs, src/bindgen/parser.rs, tests/expectations/decl_name_conflicting.both.c, tests/expectations/decl_name_conflicting.both.compat.c, tests/expectations/decl_name_conflicting.c, tests/expectations/decl_name_conflicting.compat.c, tests/expectations/decl_name_conflicting.cpp, tests/expectations/decl_name_conflicting.pyx, tests/expectations/decl_name_conflicting.tag.c, tests/expectations/decl_name_conflicting.tag.compat.c, tests/expectations/decl_name_conflicting.tag.pyx, tests/rust/decl_name_conflicting.rs
So, basically, make opaque items last, and make previous names override
them.
Fixes #649
=> ir: Deal with name conflicts correctly in declaration type resolution.

src/bindgen/config.rs, src/bindgen/ir/cfg.rs, src/bindgen/ir/ty.rs, tests/expectations/zst.both.c, tests/expectations/zst.both.compat.c, tests/expectations/zst.c, tests/expectations/zst.compat.c, tests/expectations/zst.cpp, tests/expectations/zst.pyx, tests/expectations/zst.tag.c, tests/expectations/zst.tag.compat.c, tests/expectations/zst.tag.pyx, tests/rust/zst.rs
=> ir: Support pointers to zsts.

src/bindgen/ir/ty.rs, tests/expectations/simplify_option_ptr.both.c, tests/expectations/simplify_option_ptr.both.compat.c, tests/expectations/simplify_option_ptr.c, tests/expectations/simplify_option_ptr.compat.c, tests/expectations/simplify_option_ptr.cpp, tests/expectations/simplify_option_ptr.pyx, tests/expectations/simplify_option_ptr.tag.c, tests/expectations/simplify_option_ptr.tag.compat.c, tests/expectations/simplify_option_ptr.tag.pyx, tests/rust/simplify_option_ptr.rs
Stuff like `*mut Option<&mut Foo>` should really be `*mut *mut Foo` for
example.
=> ir: simplify_standard_types should be recursive.

src/bindgen/rename.rs
This should be backwards-compatible in practice since `IdentifierType`
is `Copy`. In theory it's not though, as someone _might_ be passing that
function by name to something that requires that exact signature.
=> Fix new clippy lint clippy::wrong-self-convention

src/bindgen/parser.rs, tests/expectations/mod_2015.both.c, tests/expectations/mod_2015.both.compat.c, tests/expectations/mod_2015.c, tests/expectations/mod_2015.compat.c, tests/expectations/mod_2015.cpp, tests/expectations/mod_2015.pyx, tests/expectations/mod_2015.tag.c, tests/expectations/mod_2015.tag.compat.c, tests/expectations/mod_2015.tag.pyx, tests/expectations/mod_2018.both.c, tests/expectations/mod_2018.both.compat.c, tests/expectations/mod_2018.c, tests/expectations/mod_2018.compat.c, tests/expectations/mod_2018.cpp, tests/expectations/mod_2018.pyx, tests/expectations/mod_2018.tag.c, tests/expectations/mod_2018.tag.compat.c, tests/expectations/mod_2018.tag.pyx, tests/rust/mod_2015/src/nested/mod.rs, tests/rust/mod_2015/src/nested/other3/other4.rs, tests/rust/mod_2018/src/nested.rs, tests/rust/mod_2018/src/nested/other3/other4.rs
As seen in hashbrown:
#[cfg(feature = "raw")]
/// Experimental and unsafe `RawTable` API. This module is only available if the
/// `raw` feature is enabled.
pub mod raw {
// The RawTable API is still experimental and is not properly documented yet.
#[allow(missing_docs)]
#[path = "mod.rs"]
mod inner;
pub use inner::*;
#[cfg(feature = "rayon")]
pub mod rayon {
pub use crate::external_trait_impls::rayon::raw::*;
}
}
=> parser: Fix handling of #[path] attributes inside inline submodules.

src/bindgen/ir/enumeration.rs, src/bindgen/ir/structure.rs, src/bindgen/ir/typedef.rs, src/bindgen/ir/union.rs, src/bindgen/monomorph.rs, tests/expectations/infinite-recursion-typedef-monomorph.compat.c, tests/expectations/infinite-recursion-typedef-monomorph.cpp, tests/expectations/infinite-recursion-typedef-monomorph.pyx, tests/expectations/infinite_recursion_typedef_monomorph.compat.c, tests/expectations/infinite_recursion_typedef_monomorph.cpp, tests/expectations/infinite_recursion_typedef_monomorph.pyx, tests/rust/infinite_recursion_typedef_monomorph.rs
That way the check to prevent double-instantiation also works to prevent
infinite recursion.
=> ir: Tweak monomorphization to instantiate recursively after inserting to the replacements map.

src/bindgen/builder.rs, src/bindgen/cargo/cargo.rs, src/bindgen/cargo/cargo_metadata.rs, src/bindgen/config.rs, src/bindgen/parser.rs, src/main.rs
cbindgen invokes `cargo metadata` to find the sources of dependencies so
that it can generate bindings for types that originate in those
dependencies. However, `cargo metadata` defaults to fetching
dependencies for _all_ platforms unless it is specifically invoked with
the `--filter-platforms` argument.
This PR makes cbindgen pass that argument to `cargo metadata` using the
host platform, which will significantly reduce the time of the first
call in cases where the dependency tree includes many target-specific
dependencies.
Fixes #675.
=> Only fetch dependencies for current platform by default

docs.md, src/bindgen/ir/ty.rs, tests/expectations/pin.both.c, tests/expectations/pin.both.compat.c, tests/expectations/pin.c, tests/expectations/pin.compat.c, tests/expectations/pin.cpp, tests/expectations/pin.pyx, tests/expectations/pin.tag.c, tests/expectations/pin.tag.compat.c, tests/expectations/pin.tag.pyx, tests/rust/pin.rs, tests/rust/pin.toml
cbindgen already simplifies `MaybeUninit<T>` and `ManuallyDrop<T>` to `T`. This adds `Pin<T>` as well.
=> Simplify Pin<T> to T

docs.md, src/bindgen/cargo/cargo_expand.rs, src/bindgen/config.rs, src/bindgen/error.rs
`--pretty` is gone as of https://github.com/rust-lang/rust/pull/83491
=> Update --pretty=expanded to -Zunpretty=expanded

docs.md, src/bindgen/config.rs, src/bindgen/ir/documentation.rs, template.toml, tests/expectations/doclength_short.c, tests/expectations/doclength_short.compat.c, tests/expectations/doclength_short.cpp, tests/expectations/doclength_short.pyx, tests/rust/doclength_short.rs, tests/rust/doclength_short.toml, tests/tests.rs
When the "short" option is used, only the first line of the docs is output for each item.
The motivation for this change is to encourage writing longer docs with examples, while still keeping the header file more concise. The header file top can include a link to the full published docs instead.
=> Add documentation_style to with short and full options

src/bindgen/ir/enumeration.rs, tests/expectations/annotation.pyx, tests/expectations/annotation.tag.pyx, tests/expectations/asserted_cast.pyx, tests/expectations/asserted_cast.tag.pyx, tests/expectations/derive_ostream.pyx, tests/expectations/derive_ostream.tag.pyx, tests/expectations/destructor_and_copy_ctor.pyx, tests/expectations/destructor_and_copy_ctor.tag.pyx, tests/expectations/enum.pyx, tests/expectations/enum.tag.pyx, tests/expectations/enum_self.pyx, tests/expectations/enum_self.tag.pyx, tests/expectations/prefix.pyx, tests/expectations/prefix.tag.pyx, tests/expectations/transform_op.pyx, tests/expectations/transform_op.tag.pyx
The common `tag` should already be enough, all other tags are identical to it.
In Cython case they only create noise because the declarations only introduce names and do not determine layouts.
=> Cython: Omit per-variant tags in unions generated for Rust enums

src/bindgen/ir/constant.rs, tests/expectations/associated_in_body.both.c, tests/expectations/associated_in_body.both.compat.c, tests/expectations/associated_in_body.c, tests/expectations/associated_in_body.compat.c, tests/expectations/associated_in_body.cpp, tests/expectations/associated_in_body.pyx, tests/expectations/associated_in_body.tag.c, tests/expectations/associated_in_body.tag.compat.c, tests/expectations/associated_in_body.tag.pyx, tests/expectations/bitflags.both.c, tests/expectations/bitflags.both.compat.c, tests/expectations/bitflags.c, tests/expectations/bitflags.compat.c, tests/expectations/bitflags.cpp, tests/expectations/bitflags.pyx, tests/expectations/bitflags.tag.c, tests/expectations/bitflags.tag.compat.c, tests/expectations/bitflags.tag.pyx, tests/rust/associated_in_body.rs, tests/rust/bitflags.rs
These are useful for bitflags.
=> constant: Add support for associated constant expressions.

docs.md
This moves the documentation of `usize_is_size_t` in the correct section of docs.md.
Fix #753
=> Move the documentation of `usize_is_size_t` in the correct section of docs.md

Cargo.toml
While the Cargo.lock has 1.0.89, the current minimal version in Cargo.toml
is 1.0.3, which cannot parse modern Rust code. This leads to some
downstreams (*cough* Debian) inadvertently building cbindgen against
older versions of syn and the resulting cbindgen, even if it is the last
version, not being able to parse recent Rust code.
Bumping the version in Cargo.toml alleviates this to some extent. A
quick scan of the syn logs suggests 1.0.88 is the last version where
parsing support relevant to stable Rust syntax was added.
=> Update syn dependency to at least 1.0.88

src/bindgen/ir/generic_path.rs, tests/expectations/const_generics_thru.both.c, tests/expectations/const_generics_thru.both.compat.c, tests/expectations/const_generics_thru.c, tests/expectations/const_generics_thru.compat.c, tests/expectations/const_generics_thru.cpp, tests/expectations/const_generics_thru.pyx, tests/expectations/const_generics_thru.tag.c, tests/expectations/const_generics_thru.tag.compat.c, tests/expectations/const_generics_thru.tag.pyx, tests/rust/const_generics_thru.rs
See #761. The test case that triggers the bug is like this:
```rust
#[repr(C)]
pub struct Inner<const N: usize> {
pub bytes: [u8; N],
}
#[repr(C)]
pub struct Outer<const N: usize> {
pub inner: Inner<N>, // BUG: declares two different structs named `Inner_N`
}
...code that uses Outer<1> and Outer<2>...
```
When monomorphizing `Outer<1>`, specializing the type `Inner<N>` should result in `Inner<1>`, but it produced `Inner<N>` instead. This happens because `N` was initially parsed as a type, not a constant, so we were thoughtlessly calling `Type::specialize` on it. This can't possibly work; the desired answer `1` is not a type.
The fix is to explicitly handle this special case where the identifier was initially parsed as a type but it's a const.
=> Fix specialization of `SomeType<N>` when `N` is a const parameter.

src/bindgen/builder.rs
I noticed recently that the `cpp_compat` flag isn't available when using the builder, so I figured I'd open a PR.
=> Add with_cpp_compat to the builder

src/bindgen/builder.rs, src/bindgen/library.rs
The original fix was supposed to avoid infinitely expanding the macros when cbindgen was generated in `build.rs` with the `parse.expand` option.
However, it was not completely fixing the issue: a call to `parse_lib` which triggers the infinite recursion occurs before the old check was actually done (in the parent `generate` method).
Here, the check is simply done earlier to completely avoid the infinite loop.
I believe this fix would resolve #758.
=> Move expand infinite recursion fix

.clippy.toml, .github/workflows/cbindgen.yml, README.md, src/bindgen/cargo/cargo_metadata.rs, src/bindgen/cdecl.rs, src/bindgen/dependencies.rs, src/bindgen/ir/annotation.rs, src/bindgen/ir/item.rs, src/bindgen/ir/ty.rs, src/bindgen/parser.rs, src/bindgen/writer.rs, src/main.rs, tests/tests.rs
The MSRV is currently Rust 1.54.
- Update the badge in the Readme specifying the MSRV
- Update the .clippy.toml to the current MSRV
- Fix clippy warnings after updating the clippy.toml
The individual steps of fixing the warnings are in seperate commits for easier review. Should probably be squashed before merging.
=> Fix MSRV documentation and clippy warnings from 1.40 -> 1.54

.github/workflows/cbindgen.yml, .github/workflows/deploy.yml
Fixes the following warning:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions-rs/cargo@v1, actions-rs/toolchain@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
You can see the warnings at the bottom of example this job: https://github.com/eqrion/cbindgen/actions/runs/4366109547
Steps:
- upgrade checkout to v3
- Replace the actions-rs/cargo action, by simply calling cargo from the commandline. I don't see why one would want to involve a node.js action there in the first place.
- Replace the actions-rs/toolchain with dtolnays version, which uses the shell instead of node.js
=> CI: Fix warnings in Github actions

CHANGES, Cargo.lock, Cargo.toml
Updated the version in Cargo.toml & the changelist, and then ran `cargo update`.
This is in support of #821.
=> Bump version to v0.24.4

src/main.rs
Previously config files next to an explicit input file could not be picked up, since the `from_root_or_default` functions assumes the input path is a directory.
This is the case for all other usages of the function, but in this case we know the input is a file, so we should determine the parent directory and look for the config file in that directory. There can't be a folder with the same name as the input file, so it's not possible that we won't pick up any files anymore that we previously did.
=> Look for config files next to input files

Cargo.lock, Cargo.toml, src/main.rs
This also removes the dependency on the unmaintained crate atty.
Closes #828
=> Upgrade clap 3 to clap 4

.github/workflows/deploy.yml, CHANGES
This MR restores the release action, which creates a github release upon tag.
We now use the github-cli to release the release instead of the third party action, which is not allowed by mozilla.
=>  CI: Restore release action and add semver checks to CI deploy job

.github/workflows/deploy.yml
I forgot forcing stable rustc for semver-checks in commit 67fea1a. On nightly Rust it is possible for the rustdoc version to be newer than what cargo semver checks supports.
This time the automatic draft release should work, I tested on my fork: https://github.com/jschwe/cbindgen/actions/runs/5978102354/job/16219504446
=> Fix cargo semver-checks rust version

.clippy.toml, src/bindgen/config.rs, src/bindgen/ir/repr.rs, src/bindgen/rename.rs, tests/depfile.rs, tests/tests.rs
the msrv was bumped in in the Cargo.toml #847 but not in clippy.toml, clippy was complaining at startup and defaulting to 1.57
=> Bump clippy msrv to 1.64

docs.md
`no-export` is an already-existing annotation to skip emitting an item - this PR just documents it.
=> Add docs for no-export

CHANGES, src/bindgen/config.rs
Previously the `depfile` option added a new private member to the `Config` struct - a breaking change which many users complained about. Making the field public, but hiding it from the documentation and excluding it from `serde` reverts the breakage, while keeping the depfile functionality.
I also considered adding an `InternalConfig` struct, but this would require breaking changes to at least `Config::from_file()` and `Config::from_root_or_default()`, which is a lot more invasive than my PR.
Closes #908
=> Fix `..Default::default()` for struct `Config`

src/bindgen/cargo/cargo.rs
- this is useful in a setting where several crates may share the same name in e.g. a semver trick setting https://github.com/dtolnay/semver-trick to allow adding compatibility code to older versions of a crate to allow users to migrate towards newer version of a crate
- this is a pure addition and should keep all existing behaviors exactly the same
this is a PR that attemps to solve https://github.com/mozilla/cbindgen/issues/900 in a way that does not break anything that already works with cbindgen as this is a pure addition to the code base leaving all existing behaviors untouched (other solutions may involve canonicalizing paths which may panic in places where there were no panics and may cause issues for any build systems with symlinks and network disks).
This is akin to cargo's …
=> feat: allow users to specify a crate version for bindings generation

src/bindgen/ir/item.rs
This mutation can be done in-place with `retain` on both the `IndexMap` and its inner `Cfg(Vec)` values. In addition to being simpler, it should be a little faster since it doesn't need new allocations nor re-hashing of retained items.
=> Use `retain` in `ItemMap::filter`

docs.md, src/bindgen/config.rs, src/bindgen/ir/annotation.rs, src/bindgen/ir/enumeration.rs, tests/expectations/deprecated.c, tests/expectations/deprecated.compat.c, tests/expectations/deprecated.cpp, tests/expectations/deprecated.pyx, tests/expectations/deprecated_both.c, tests/expectations/deprecated_both.compat.c, tests/expectations/deprecated_tag.c, tests/expectations/deprecated_tag.compat.c, tests/expectations/deprecated_tag.pyx, tests/rust/deprecated.rs, tests/rust/deprecated.toml
While the `#[deprecated]` attribute was already used on structs, fns and enums, it was not implemented for enum variants. The information about enum variants is already available via `variant.body.annotations`, so the support for the `#[deprecated] `attribute on enum-variant level is more or less only another pair of entries within the `EnumConfig`.
This commit adds two new options within the `[enum]` settings:
- `deprecated_variant`, and
- `deprecated_variant_with_notes`
Both get active only on #[deprecated] variants, e.g.,
#[repr(u8)]
enum ApiLevel {
#[deprecated(note = "Legacy Support until 2025")]
L1 = 1,
#[deprecated]
L2 = 2,
L3 = 3,
L4 = 4,
}
For enums with struct variants, the current struct deprecation methods are already working good enough (see `tests/expecations/deprecated*`). …
=> feat: support #[deprecated] on enum variants

src/bindgen/parser.rs, tests/expectations/cfg.c, tests/expectations/cfg.compat.c, tests/expectations/cfg.cpp, tests/expectations/cfg.pyx, tests/expectations/cfg_both.c, tests/expectations/cfg_both.compat.c, tests/expectations/cfg_tag.c, tests/expectations/cfg_tag.compat.c, tests/expectations/cfg_tag.pyx, tests/rust/cfg.rs
=> Account for cfg items in foreign mods.

src/bindgen/parser.rs, tests/expectations/extern.c, tests/expectations/extern.compat.c, tests/expectations/extern.cpp, tests/expectations/extern.pyx, tests/expectations/extern_both.c, tests/expectations/extern_both.compat.c, tests/expectations/extern_tag.c, tests/expectations/extern_tag.compat.c, tests/expectations/extern_tag.pyx, tests/rust/extern.rs
As per https://doc.rust-lang.org/reference/items/external-blocks.html#abi
Closes #709
=> parser: Treat omitted ABI in extern block as "C".

src/bindgen/parser.rs, src/bindgen/utilities.rs, tests/expectations/ignore.c, tests/expectations/ignore.compat.c, tests/expectations/ignore.cpp, tests/expectations/ignore.pyx, tests/rust/ignore.rs
Fix for https://github.com/mozilla/cbindgen/issues/947
Add missing checks so that cbindgen honors `cbindgen:ignore` directives for associated functions and constants declared inside a struct impl.
=> Honor cbindgen:ignore directives for associated functions and constants

Cargo.toml, tests/depfile/single_crate_config/Cargo.lock, tests/depfile/single_crate_config/Cargo.toml, tests/depfile/single_crate_default_config/Cargo.lock, tests/depfile/single_crate_default_config/Cargo.toml
Otherwise, `cargo` prints a warning when using `cbindgen` as a `build-dependency` in my workspace:
```
warning: skipping duplicate package `single_crate` found at `/Users/gferon/.cargo/git/checkouts/cbindgen-4f7d248bb26fc43d/10f32b0/tests/depfile/single_crate`
warning: skipping duplicate package `single_crate` found at `/Users/gferon/.cargo/git/checkouts/cbindgen-4f7d248bb26fc43d/10f32b0/tests/depfile/single_crate_default_config`
```
=> Rename duplicate crate in workspace

src/bindgen/utilities.rs
As per title, remove debugging code accidentally introduced by https://github.com/mozilla/cbindgen/pull/949
=> Revert accidentally committed debug code

Cargo.lock, Cargo.toml, tests/tests.rs
The `pretty_assert` package makes it much (much) easier to compare expected vs. actual output when a test fails. Example:
=> Update tests.rs to use pretty_assertions for readable diffs

src/bindgen/ir/constant.rs, tests/expectations/const_transparent.compat.c, tests/expectations/const_transparent.cpp, tests/expectations/const_transparent.pyx, tests/rust/const_transparent.rs
When defining a constant of multiply-nested transparent struct type, the struct is reduced to typedefs and so the extra layers of constant initializer need to be removed. The existing code only removed one layer. Fixed by changing the check to a loop.
Without the fix, a declaration like this:
```rust
#[repr(transparent)]
struct TransparentStruct { field: u8 }
#[repr(transparent)]
struct Foo<T> { field: T }
#[repr(transparent)]
struct Bar<T> {
field: Foo<T>,
}
pub const BAR: Bar<TransparentStruct> =
Bar { field: Foo { field: TransparentStruct { field: 7 } } };
```
exports as 
```cpp
constexpr static const Bar<TransparentStruct> BAR =
Foo { /* .field = */ TransparentStruct{ /* .field = */ 7 } };
```
instead of the desired
```cpp
constexpr static const Bar<TransparentStruct> BAR = 7;
```
=> Handle constants of nested transparent types

src/bindgen/ir/generic_path.rs, tests/expectations/generic_defaults.c, tests/expectations/generic_defaults.compat.c, tests/expectations/generic_defaults.cpp, tests/expectations/generic_defaults.pyx, tests/expectations/generic_defaults_both.c, tests/expectations/generic_defaults_both.compat.c, tests/expectations/generic_defaults_tag.c, tests/expectations/generic_defaults_tag.compat.c, tests/expectations/generic_defaults_tag.pyx, tests/rust/generic_defaults.rs
Rust allows generics with defaulted arguments, such as:
```rust
#[repr(transparent)]
pub struct Foo<T, P = c_void> {
field: T,
_phantom: std::marker::PhantomData<P>,
}
```
However, any usage that actually relies on such default(s) can trigger assertion failures, e.g.
```rust
#[repr(C)]
pub struct Bar<T> {
f: Foo<T>,
}
```
or 
```rust
pub type Baz<T> = Foo<T>;
```
Fails with
```
cbindgen failed: None with error: thread 'main' panicked at src/bindgen/ir/generic_path.rs:85:9:
Foo has 2 params but is being instantiated with 1 values
stack backtrace:
0: rust_begin_unwind
at /rustc/c987ad527540e8f1565f57c31204bde33f63df76/library/std/src/panicking.rs:652:5
1: core::panicking::panic_fmt
at /rustc/c987ad527540e8f1565f57c31204bde33f63df76/library/core/src/panicking.rs:72:14
2: …
```
=> Support generics with defaulted args

docs.md
This is a trap "for young players" and loosing feedback from rustc or your favorite code analysis tools won't make things better. Let's point out the issue and the solution given in issue #472 upfront.
=> Point out issue with failing user builds due to syntax errors

src/bindgen/ir/function.rs, src/bindgen/ir/ty.rs, tests/expectations/va_list.c, tests/expectations/va_list.compat.c, tests/expectations/va_list.cpp, tests/expectations/va_list.pyx, tests/expectations/va_list_both.c, tests/expectations/va_list_both.compat.c, tests/expectations/va_list_tag.c, tests/expectations/va_list_tag.compat.c, tests/expectations/va_list_tag.pyx, tests/rust/va_list.rs
From what I can tell a `va_list` should be created by calling [`va_start`](https://en.cppreference.com/w/c/variadic/va_start) and no documentation that I could find specifies the use of `va_list` as an argument explicitly. 
Assuming this works, I imagine that some compilers happen to implement `va_list` and `...` the same, but `...` seems the be the specified way.
I haven't done any runtime testing of these changes, so if this is wrong I'd love to know why.
Sources:
* https://en.cppreference.com/w/c/language/variadic
* https://en.cppreference.com/w/cpp/language/variadic_arguments
Related: https://github.com/mozilla/cbindgen/pull/968
Closes: https://github.com/mozilla/cbindgen/issues/891
=> Va list binding compatibility

src/bindgen/language_backend/clike.rs, src/bindgen/language_backend/cython.rs, tests/expectations/cfg.c, tests/expectations/cfg.compat.c, tests/expectations/cfg.cpp, tests/expectations/cfg.pyx, tests/expectations/cfg_both.c, tests/expectations/cfg_both.compat.c, tests/expectations/cfg_tag.c, tests/expectations/cfg_tag.compat.c, tests/expectations/cfg_tag.pyx, tests/rust/cfg.rs
I was getting an error in a global array that has a different size when a feature is enabled.
This PR fixes the issue.
=> Output condition for globals.

CHANGES
Helps for [the comment](https://github.com/mozilla/cbindgen/pull/912#issuecomment-2136195600) in #912.
I had no extensive knowledge about the details of this project before, so I selected some of the PRs since Sep 14, 2023, based on my understanding, and added them to the changelog. I hope this helps the preparations for a new release.
=> Update CHANGES since v0.26.0

src/bindgen/ir/enumeration.rs
Fixes #808 using @emilio's suggestion in https://github.com/mozilla/cbindgen/issues/808#issuecomment-1460383144
=> Fix local override of enum prefix-with-name

src/bindgen/ir/enumeration.rs, src/bindgen/ir/function.rs, src/bindgen/ir/structure.rs, src/bindgen/ir/union.rs, src/bindgen/mangle.rs, src/bindgen/rename.rs, tests/expectations/rename_case.c, tests/expectations/rename_case.compat.c, tests/expectations/rename_case.cpp, tests/expectations/rename_case.pyx, tests/rust/rename_case.rs
This is #1007 but with nits and a test.
Closes #1007
=> Add rename-all=prefix

src/bindgen/mangle.rs, tests/expectations/generic_pointer.c, tests/expectations/generic_pointer.compat.c, tests/expectations/generic_pointer.cpp, tests/expectations/generic_pointer.pyx, tests/expectations/generic_pointer_both.c, tests/expectations/generic_pointer_both.compat.c, tests/expectations/generic_pointer_tag.c, tests/expectations/generic_pointer_tag.compat.c, tests/expectations/generic_pointer_tag.pyx, tests/rust/generic_pointer.rs
This is #1008 but with a test.
Closes #1008
=> Implement mangling for arrays

src/bindgen/ir/constant.rs, src/bindgen/language_backend/clike.rs, tests/expectations/associated_in_body.cpp, tests/expectations/bitflags.cpp, tests/expectations/const_generics_constant.cpp, tests/expectations/constant_constexpr.cpp, tests/expectations/constant_user_defined_type.cpp, tests/expectations/prefixed_struct_literal.cpp, tests/expectations/prefixed_struct_literal_deep.cpp, tests/expectations/struct_literal.cpp, tests/expectations/struct_literal_order.cpp
generate newline for each constexpr literal structs' fields
A shared patch to branch #956 and #989
=> Newline for each field for constexpr field constants

.github/workflows/cbindgen.yml
fixes #1032
This is a proof of concept to build and test arm64 executables. If this concept is acceptable then I would like to refactor to a "strategy matrix" build.
edit: The last build in my repo is successful: https://github.com/NickeZ/cbindgen/actions/runs/12596962803/job/35109043466, so hopefully this rebased version also works.
=> Add aarch64/arm64 to CI

Cargo.toml, docs.md, src/bindgen/mod.rs, src/lib.rs
=> Add `unstable_ir` feature flag that makes the ir pub

src/bindgen/ir/generic_path.rs, tests/expectations-symbols/generic_defaults.c.sym, tests/expectations/generic_defaults.c, tests/expectations/generic_defaults.compat.c, tests/expectations/generic_defaults.cpp, tests/expectations/generic_defaults.pyx, tests/expectations/generic_defaults_both.c, tests/expectations/generic_defaults_both.compat.c, tests/expectations/generic_defaults_tag.c, tests/expectations/generic_defaults_tag.compat.c, tests/expectations/generic_defaults_tag.pyx, tests/rust/generic_defaults.rs
=> Fix generic with "void" default

docs.md
The property is called `deprecated_with_note`, but docs.toml incorrectly spells it as `deprecated_with_notes`. The same applies to `deprecated_variant_with_note`.
https://github.com/mozilla/cbindgen/blob/0328601dc1a827d761913e1e08ccb3295c5b0c8a/src/bindgen/config.rs#L422
=> docs.md: Fix deprecated_with_note and deprecated_variant_with_note being spelled as 'notes'

Cargo.lock, Cargo.toml
The breaking change doesn't affect.
The change 0.4 to 0.5 is about `unicode` feature, which is not used in this project.
=> Upgrade heck to 0.5

.github/workflows/deploy.yml
cross compiler package (gcc-11-aarch64-linux-gnu) only available starting with 22.04
Currently running test deploy here: https://github.com/NickeZ/cbindgen/actions/runs/14291327838/job/40052936519
---
edit: 
It does create the draft release, but only one artifact ends up there. Not sure what I'm doing wrong, I think the `gh release create` command should take multiple files.
```
HTTP 404: Not Found (https://uploads.github.com/repos/NickeZ/cbindgen/releases/210598162/assets?label=cbindgen-ubuntu22.04&name=cbindgen)
Error: Process completed with exit code 1.
```
---
edit2:
Fixed the issue and rebased: https://github.com/NickeZ/cbindgen/actions/runs/14409080964/job/40412556524
=> Github action: Add aarch64 to deploy

.clippy.toml, Cargo.toml, src/bindgen/bindings.rs, src/bindgen/builder.rs, src/bindgen/cargo/cargo_expand.rs, src/bindgen/cdecl.rs, src/bindgen/config.rs, src/bindgen/error.rs, src/bindgen/ir/annotation.rs, src/bindgen/ir/cfg.rs, src/bindgen/ir/constant.rs, src/bindgen/ir/enumeration.rs, src/bindgen/ir/function.rs, src/bindgen/ir/generic_path.rs, src/bindgen/ir/repr.rs, src/bindgen/ir/structure.rs, src/bindgen/ir/ty.rs, src/bindgen/language_backend/clike.rs, src/bindgen/language_backend/cython.rs, src/bindgen/language_backend/mod.rs, src/bindgen/rename.rs, src/bindgen/writer.rs, tests/depfile.rs, tests/tests.rs
I updated to 2021 edition so this could be consistently applied in panic
and assert messages as well. There were no changes suggested by
`cargo fix --edition` beforehand, and the MSRV is unchanged.
I also removed `.clippy.toml` because Clippy uses `package.rust-version`
these days, and it was warning that these had different versions.
=> Fix `clippy::uninlined_format_args`
