src/bindgen/mangle.rs
mangle_name converts `Foo<Bar>` into `Foo_Bar`, and asserts
that the parent type name doesn't already contain underscores.
Report the offending type in the assert message so it's easier
to track down the problem, and add a unit test for this requirement.
=> Improve error message for generic types with underscores.

test.py
Ensures that Python is correctly found across different platforms.
=> Fix test.py shebang

src/bindgen/ir/enumeration.rs, src/bindgen/ir/structure.rs, tests/expectations/alias.c, tests/expectations/alias.cpp, tests/expectations/annotation.c, tests/expectations/annotation.cpp, tests/expectations/cfg.c, tests/expectations/cfg.cpp, tests/expectations/enum.c, tests/expectations/enum.cpp, tests/rust/enum.rs
I've come to realise that I can't find time to continue refactoring generics or to implement them by duplicating methods from other item types, so decided to at least rebase my branch with tagged enums as they are (without generics) to close #78.
Sorry for this taking so long and being somewhat unfinished.
=> Non-generic support for tagged enums

src/bindgen/ir/enumeration.rs, src/bindgen/ir/repr.rs, src/bindgen/ir/structure.rs, src/bindgen/ir/union.rs, tests/expectations/display_list.cpp, tests/expectations/enum.c, tests/expectations/enum.cpp, tests/rust/enum.rs
- Implement support for repr(C, Int) (fixes #119)
- Fix wrapper kind for C-like tagged enum (fixes #126)
- Wrap tag into anonymous struct in C++ (fixes #122)
cc @Gankro
=> Fixes and improvements for tagged enums

src/bindgen/builder.rs
This PR enables `Builder` to accept the path to "Cargo.lock".
It is useful when working on the multiple workspaces.
=> Add Builder.with_lockfile

src/bindgen/parser.rs
=> Provide a better error when parsing a module fails.

src/bindgen/ir/enumeration.rs, src/bindgen/ir/structure.rs, tests/expectations/both/derive-eq.c, tests/expectations/derive-eq.c, tests/expectations/derive-eq.cpp, tests/expectations/tag/derive-eq.c, tests/rust/derive-eq/Cargo.lock, tests/rust/derive-eq/Cargo.toml, tests/rust/derive-eq/cbindgen.toml, tests/rust/derive-eq/src/lib.rs
This will make https://bugzilla.mozilla.org/show_bug.cgi?id=1429298 not write it manually.
=> Honor derive_eq / derive_neq for unions.

src/bindgen/bindings.rs, src/bindgen/builder.rs, src/bindgen/cdecl.rs, src/bindgen/ir/constant.rs, src/bindgen/ir/enumeration.rs, src/bindgen/ir/function.rs, src/bindgen/ir/generics.rs, src/bindgen/ir/item.rs, src/bindgen/ir/repr.rs, src/bindgen/ir/structure.rs, src/bindgen/ir/union.rs, src/bindgen/parser.rs, src/bindgen/writer.rs, tests/expectations/assoc_constant.c, tests/expectations/assoc_constant.cpp, tests/expectations/both/assoc_constant.c, tests/expectations/both/struct_literal.c, tests/expectations/struct_literal.c, tests/expectations/struct_literal.cpp, tests/expectations/tag/assoc_constant.c, tests/expectations/tag/struct_literal.c, tests/rust/assoc_constant.rs, tests/rust/struct_literal.rs
This solves #100 albeit with some caveats and limitations. Check the commit messages for more details.
=> Add support for associated constants and struct literals

README.md
=> added installation

src/bindgen/ir/item.rs, tests/expectations/both/item_types_renamed.c, tests/expectations/item_types_renamed.c, tests/expectations/item_types_renamed.cpp, tests/expectations/tag/item_types_renamed.c, tests/rust/item_types_renamed.rs, tests/rust/item_types_renamed.toml
This broke mozilla-central once, hopefully not twice :)
=> Test the interaction between include and prefix configurations.

src/bindgen/cdecl.rs, src/bindgen/ir/ty.rs, tests/expectations/both/cdecl.c, tests/expectations/both/fns.c, tests/expectations/cdecl.c, tests/expectations/cdecl.cpp, tests/expectations/fns.c, tests/expectations/fns.cpp, tests/expectations/tag/cdecl.c, tests/expectations/tag/fns.c, tests/rust/cdecl.rs, tests/rust/fns.rs
This resolves https://github.com/eqrion/cbindgen/issues/180.
=> Preserve fn type argument names

src/bindgen/ir/constant.rs, src/bindgen/ir/enumeration.rs, tests/expectations/both/enum.c, tests/expectations/enum.c, tests/expectations/enum.cpp, tests/expectations/tag/enum.c, tests/rust/enum.rs
Pretty straight-forward, but it bit me today :)
=> ir: Add support for negative enum discriminants.

src/bindgen/ir/annotation.rs, src/bindgen/ir/documentation.rs, src/bindgen/utilities.rs
=> Fix bad doc comment processing

src/bindgen/ir/ty.rs
=> Add support for ssize_t

src/bindgen/builder.rs, src/bindgen/config.rs
This makes few more final APIs that work with files consistent with the rest.
Fixes #280.
=> Update few more APIs to use AsRef<Path>

src/bindgen/cargo/cargo_expand.rs, src/bindgen/cargo/cargo_metadata.rs, src/bindgen/cargo/cargo_toml.rs, src/bindgen/error.rs
=> Impl std::error::Error for cbindgen::Error

src/bindgen/bindings.rs, tests/expectations/both/include_specific.c, tests/expectations/include_specific.c, tests/expectations/include_specific.cpp, tests/expectations/tag/include_specific.c, tests/rust/include_specific.toml
=> Added support for includes without default

src/bindgen/bindings.rs, src/bindgen/bitflags.rs, src/bindgen/ir/constant.rs, src/bindgen/ir/structure.rs, src/bindgen/parser.rs, tests/expectations/associated_in_body.cpp, tests/expectations/bitflags.cpp, tests/expectations/both/struct_literal.c, tests/expectations/struct_literal.c, tests/expectations/struct_literal.cpp, tests/expectations/tag/struct_literal.c, tests/rust/struct_literal.rs
This is all I need to enable the feature in Gecko and replace all manual bindings for bitflags.
=> More bitflags improvements.

src/bindgen/ir/constant.rs, src/bindgen/ir/generic_path.rs, src/bindgen/ir/path.rs, src/bindgen/ir/ty.rs, tests/expectations/both/struct_literal.c, tests/expectations/struct_literal.c, tests/expectations/struct_literal.cpp, tests/expectations/tag/struct_literal.c, tests/rust/struct_literal.rs
WebRender used to do this and it's not hard to handle. This ensures that you can bisect Gecko manually without a lot of issues.
=> constant: Handle Self in associated constants.

src/bindgen/ir/constant.rs, tests/expectations/both/constant.c, tests/expectations/constant.c, tests/expectations/constant.cpp, tests/expectations/tag/constant.c, tests/rust/constant.rs
Signed-off-by: Axel Nennker <axel.nennker@telekom.de>
trying to fix https://github.com/eqrion/cbindgen/issues/317
=> put apostrophe around char constant

src/bindgen/ir/constant.rs, tests/expectations/both/constant.c, tests/expectations/constant.c, tests/expectations/constant.cpp, tests/expectations/tag/constant.c, tests/rust/constant.rs
Signed-off-by: Axel Nennker <axel.nennker@telekom.de>
Fix https://github.com/eqrion/cbindgen/issues/320
=> escape chars

src/bindgen/ir/constant.rs, tests/expectations/both/constant.c, tests/expectations/constant.c, tests/expectations/constant.cpp, tests/expectations/tag/constant.c, tests/rust/constant.rs
Signed-off-by: Axel Nennker <axel.nennker@telekom.de>
Fix https://github.com/eqrion/cbindgen/issues/205
=> fix #205 Negative literals

src/bindgen/cargo/cargo_metadata.rs
Investigating build script failures with `cbindgen` calls somewhere deep isn't fun. This change gets us from here:
> 0:04.53 ERROR: Couldn't execute `cargo metadata` with manifest "/mnt/code/firefox/toolkit/library/rust/Cargo.toml": Json(Error("EOF while parsing a value", line: 1, column: 0))
0:04.53 ERROR: Couldn't generate bindings for /mnt/code/firefox/toolkit/library/rust.
To here:
> 0:02.08 ERROR: Couldn't execute `cargo metadata` with manifest "/mnt/code/firefox/toolkit/library/rust/Cargo.toml": Metadata(Output { status: ExitStatus(ExitStatus(25856)), stdout: "", stderr: "error: no matching package named `ipc-channel` found\nlocation searched: registry `https://github.com/rust-lang/crates.io-index`\nrequired by package `wgpu-remote v0.1.0 (/mnt/code/firefox/gfx/wgpu/wgpu-remote)`\n" …
=> Dedicated error message for cargo metadata failures

tests/tests.rs
=> require c++11 to run the test suite

src/bindgen/parser.rs
Since cbindgen ignores the ident namespaces and the expected behavior is
to have it generate bindings for the idents declared in the root crate,
parse first the root crate and then its dependencies.
Fixes #337.
=> Fix the crate parsing order

.travis.yml
This uploads the cbindgen executable on tagged releases.
Fixes #351.
=> Upload binaries on releases.

src/bindgen/cargo/cargo_expand.rs, src/bindgen/cdecl.rs, src/bindgen/config.rs, src/bindgen/declarationtyperesolver.rs, src/bindgen/error.rs, src/bindgen/ir/annotation.rs, src/bindgen/ir/cfg.rs, src/bindgen/ir/constant.rs, src/bindgen/ir/enumeration.rs, src/bindgen/ir/function.rs, src/bindgen/ir/generic_path.rs, src/bindgen/ir/global.rs, src/bindgen/ir/item.rs, src/bindgen/ir/opaque.rs, src/bindgen/ir/structure.rs, src/bindgen/ir/ty.rs, src/bindgen/ir/typedef.rs, src/bindgen/library.rs, src/bindgen/parser.rs, src/bindgen/rename.rs, src/bindgen/reserved.rs, src/bindgen/utilities.rs, src/bindgen/writer.rs, tests/expectations/std_lib.compat.c
Greetings everyone,
I just fixed the clippy warnings that do not require bigger changes (They maybe come in another PR). Hope it helpes :)
=> Fixed most of the clippy warnings

src/logging.rs, src/main.rs
=> Add support for --quiet flag

src/bindgen/bindings.rs
=> Minor refactoring to the namespaces logic.

src/bindgen/config.rs
Fixes https://github.com/eqrion/cbindgen/issues/411
This is still sub optimal since a stack trace is shown instead of a nice error
message, but at least adds a human readable context with full file path instead
of a generic 'Unwrap() went wrong".
Before:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
Now:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Couldn\'t open config file: cbindgen.toml."', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
=> Improve error message when config file is not found

docs.md, src/bindgen/config.rs, src/bindgen/library.rs, template.toml, tests/expectations/both/function_sort_name.c, tests/expectations/both/function_sort_name.compat.c, tests/expectations/both/function_sort_none.c, tests/expectations/both/function_sort_none.compat.c, tests/expectations/function_sort_name.c, tests/expectations/function_sort_name.compat.c, tests/expectations/function_sort_name.cpp, tests/expectations/function_sort_none.c, tests/expectations/function_sort_none.compat.c, tests/expectations/function_sort_none.cpp, tests/expectations/tag/function_sort_name.c, tests/expectations/tag/function_sort_name.compat.c, tests/expectations/tag/function_sort_none.c, tests/expectations/tag/function_sort_none.compat.c, tests/rust/function_sort_name.rs, tests/rust/function_sort_none.rs, tests/rust/function_sort_none.toml
=> Add option for sorting of function names

src/bindgen/mangle.rs, tests/expectations/both/generic-pointer.c, tests/expectations/both/generic-pointer.compat.c, tests/expectations/generic-pointer.c, tests/expectations/generic-pointer.compat.c, tests/expectations/generic-pointer.cpp, tests/expectations/tag/generic-pointer.c, tests/expectations/tag/generic-pointer.compat.c, tests/rust/generic-pointer.rs
Ugly, but better than crashing.
Closes #506.
Closes #453.
=> Handle mangling pointers.

docs.md, src/bindgen/ir/enumeration.rs, src/bindgen/ir/structure.rs, tests/expectations/asserted-cast.c, tests/expectations/asserted-cast.compat.c, tests/expectations/asserted-cast.cpp, tests/expectations/both/asserted-cast.c, tests/expectations/both/asserted-cast.compat.c, tests/expectations/both/destructor-and-copy-ctor.c, tests/expectations/both/destructor-and-copy-ctor.compat.c, tests/expectations/destructor-and-copy-ctor.c, tests/expectations/destructor-and-copy-ctor.compat.c, tests/expectations/destructor-and-copy-ctor.cpp, tests/expectations/tag/asserted-cast.c, tests/expectations/tag/asserted-cast.compat.c, tests/expectations/tag/destructor-and-copy-ctor.c, tests/expectations/tag/destructor-and-copy-ctor.compat.c, tests/rust/asserted-cast.rs, tests/rust/asserted-cast.toml, tests/rust/destructor-and-copy-ctor.rs, tests/rust/destructor-and-copy-ctor.toml
This will allow us to fix https://bugzilla.mozilla.org/show_bug.cgi?id=1631929 in a straight-forward way.
=> ir: Allow per-method annotations for all the auto-generated methods.

src/bindgen/ir/function.rs, tests/expectations/both/function_args.c, tests/expectations/both/function_args.compat.c, tests/expectations/function_args.c, tests/expectations/function_args.compat.c, tests/expectations/function_args.cpp, tests/expectations/tag/function_args.c, tests/expectations/tag/function_args.compat.c, tests/rust/function_args.rs
=> Do not accept array as function arguments

tests/tests.rs
=> tests: Fix errors when testing with clang.

src/bindgen/bitflags.rs, tests/expectations/associated_in_body.c, tests/expectations/associated_in_body.compat.c, tests/expectations/associated_in_body.cpp, tests/expectations/bitflags.c, tests/expectations/bitflags.compat.c, tests/expectations/bitflags.cpp, tests/expectations/both/associated_in_body.c, tests/expectations/both/associated_in_body.compat.c, tests/expectations/both/bitflags.c, tests/expectations/both/bitflags.compat.c, tests/expectations/tag/associated_in_body.c, tests/expectations/tag/associated_in_body.compat.c, tests/expectations/tag/bitflags.c, tests/expectations/tag/bitflags.compat.c, tests/rust/bitflags.rs
=> Allow 1<<31 as a bitflags value

src/bindgen/bitflags.rs, src/bindgen/builder.rs, src/bindgen/cargo/cargo.rs, src/bindgen/cargo/cargo_lock.rs, src/bindgen/cargo/cargo_metadata.rs, src/bindgen/cargo/cargo_toml.rs, src/bindgen/cargo/mod.rs, src/bindgen/config.rs, src/bindgen/declarationtyperesolver.rs, src/bindgen/dependencies.rs, src/bindgen/ir/annotation.rs, src/bindgen/ir/cfg.rs, src/bindgen/ir/constant.rs, src/bindgen/ir/documentation.rs, src/bindgen/ir/enumeration.rs, src/bindgen/ir/function.rs, src/bindgen/ir/generic_path.rs, src/bindgen/ir/global.rs, src/bindgen/ir/item.rs, src/bindgen/ir/opaque.rs, src/bindgen/ir/repr.rs, src/bindgen/ir/structure.rs, src/bindgen/ir/ty.rs, src/bindgen/ir/typedef.rs, src/bindgen/ir/union.rs, src/bindgen/library.rs, src/bindgen/parser.rs, src/bindgen/utilities.rs, src/bindgen/writer.rs, src/logging.rs
=> Fix clippy warnings

docs.md, src/bindgen/cdecl.rs, src/bindgen/ir/function.rs, tests/expectations/both/ptrs_as_arrays.c, tests/expectations/both/ptrs_as_arrays.compat.c, tests/expectations/ptrs_as_arrays.c, tests/expectations/ptrs_as_arrays.compat.c, tests/expectations/ptrs_as_arrays.cpp, tests/expectations/tag/ptrs_as_arrays.c, tests/expectations/tag/ptrs_as_arrays.compat.c, tests/rust/ptrs_as_arrays.rs
=> Add an attribute to tell cbindgen how to present pointers

docs.md, src/bindgen/config.rs, src/bindgen/ir/enumeration.rs, src/bindgen/ir/opaque.rs, src/bindgen/ir/structure.rs, src/bindgen/ir/typedef.rs, src/bindgen/ir/union.rs, src/bindgen/mangle.rs, src/bindgen/rename.rs, src/lib.rs, template.toml, tests/expectations/both/mangle.c, tests/expectations/both/mangle.compat.c, tests/expectations/mangle.c, tests/expectations/mangle.compat.c, tests/expectations/mangle.cpp, tests/expectations/tag/mangle.c, tests/expectations/tag/mangle.compat.c, tests/rust/mangle.rs, tests/rust/mangle.toml
This squashes #565 and cleans up a bit on top.
=> Pascal case primitives

src/bindgen/ir/annotation.rs, src/bindgen/ir/enumeration.rs, tests/expectations/both/derive_ostream.c, tests/expectations/both/derive_ostream.compat.c, tests/expectations/derive_ostream.c, tests/expectations/derive_ostream.compat.c, tests/expectations/derive_ostream.cpp, tests/expectations/tag/derive_ostream.c, tests/expectations/tag/derive_ostream.compat.c, tests/rust/derive_ostream.rs
=> Some followups to #582

src/bindgen/parser.rs, tests/expectations/lifetime_arg.both.c, tests/expectations/lifetime_arg.both.compat.c, tests/expectations/lifetime_arg.c, tests/expectations/lifetime_arg.compat.c, tests/expectations/lifetime_arg.cpp, tests/expectations/lifetime_arg.tag.c, tests/expectations/lifetime_arg.tag.compat.c, tests/rust/lifetime_arg.rs
Fixes https://github.com/eqrion/cbindgen/issues/485
=> Remove artificial restriction on lifetime parameters on enums

.github/workflows/deploy.yml
You can look how notes are going to be rendered [here](https://github.com/Luni-4/cbindgen/releases/tag/v0.0.1)
=> Format release notes in a better way

.github/workflows/deploy.yml
=> Add a comment to explain release notes code

src/bindgen/cdecl.rs, src/bindgen/ir/repr.rs, src/bindgen/ir/ty.rs, src/bindgen/mangle.rs, tests/expectations/nonzero.both.c, tests/expectations/nonzero.both.compat.c, tests/expectations/nonzero.c, tests/expectations/nonzero.compat.c, tests/expectations/nonzero.cpp, tests/expectations/nonzero.pyx, tests/expectations/nonzero.tag.c, tests/expectations/nonzero.tag.compat.c, tests/expectations/nonzero.tag.pyx, tests/expectations/simplify_option_ptr.both.c, tests/expectations/simplify_option_ptr.both.compat.c, tests/expectations/simplify_option_ptr.c, tests/expectations/simplify_option_ptr.compat.c, tests/expectations/simplify_option_ptr.cpp, tests/expectations/simplify_option_ptr.pyx, tests/expectations/simplify_option_ptr.tag.c, tests/expectations/simplify_option_ptr.tag.compat.c, tests/expectations/simplify_option_ptr.tag.pyx, tests/rust/nonzero.rs, tests/rust/nonzero.toml, tests/rust/simplify_option_ptr.rs
Fixes #646
Drive-by also fixes #223
=> ir: Handle NonZero and simplify Option<NonZero>

docs.md, src/bindgen/config.rs, template.toml
Fix https://github.com/eqrion/cbindgen/issues/653.
=> doc: Document the `documentation` config entry

src/bindgen/cargo/cargo_expand.rs
=> use --profile=check for macro expansion

src/bindgen/ir/constant.rs, src/bindgen/ir/enumeration.rs, src/bindgen/ir/field.rs, src/bindgen/ir/function.rs, src/bindgen/ir/generic_path.rs, src/bindgen/ir/global.rs, src/bindgen/ir/repr.rs, src/bindgen/ir/structure.rs, src/bindgen/ir/ty.rs, src/bindgen/ir/typedef.rs, src/bindgen/ir/union.rs, src/bindgen/parser.rs, src/bindgen/utilities.rs, tests/expectations/raw_ident.both.c, tests/expectations/raw_ident.both.compat.c, tests/expectations/raw_ident.c, tests/expectations/raw_ident.compat.c, tests/expectations/raw_ident.cpp, tests/expectations/raw_ident.pyx, tests/expectations/raw_ident.tag.c, tests/expectations/raw_ident.tag.compat.c, tests/expectations/raw_ident.tag.pyx, tests/rust/raw_ident.rs
Fixes https://github.com/eqrion/cbindgen/issues/410
=> unraw the identifiers

Cargo.lock
=> Update various dependencies.

src/bindgen/bindings.rs, src/bindgen/cdecl.rs, src/bindgen/config.rs, src/bindgen/ir/cfg.rs, src/bindgen/ir/function.rs, src/bindgen/ir/ty.rs, tests/expectations/function_noreturn.both.c, tests/expectations/function_noreturn.both.compat.c, tests/expectations/function_noreturn.c, tests/expectations/function_noreturn.tag.c, tests/expectations/function_noreturn.tag.compat.c, tests/expectations/function_noreturn.tag.pyx, tests/rust/function_noreturn.rs
=> Handle never type in return position consistently.

README.md
Re #787
Feel free to close and move someone else if there's a better place for this.
=> Add Homebrew instructions to readme

README.md
https://github.com/PyO3/maturin/blob/190759e804e4d10ff7e2e747c8bd76c17d6ee812/src/module_writer.rs#L461-L498
=> Add maturin to examples

.github/workflows/cbindgen.yml, .github/workflows/deploy.yml, CHANGES
=> ci: Try to fix github actions.

src/bindgen/ir/ty.rs, tests/expectations/va_list.c, tests/expectations/va_list.compat.c, tests/expectations/va_list.cpp, tests/expectations/va_list.pyx, tests/rust/va_list.rs
=> Parse `...` as a `VaList`

README.md
=> Update doc link in Readme so it works from docs.rs

Cargo.lock
Updates syn to not crash with c string literals and so on, and other crates while at it.
=> chore: Update dependencies.

Cargo.lock, Cargo.toml, src/bindgen/utilities.rs, tests/expectations/export_name.c, tests/expectations/export_name.compat.c, tests/expectations/export_name.cpp, tests/expectations/export_name.pyx, tests/expectations/mangle.c, tests/expectations/mangle.compat.c, tests/expectations/mangle.cpp, tests/expectations/mangle.pyx, tests/expectations/mangle_both.c, tests/expectations/mangle_both.compat.c, tests/expectations/mangle_tag.c, tests/expectations/mangle_tag.compat.c, tests/expectations/mangle_tag.pyx, tests/rust/export_name.rs, tests/rust/mangle.rs
This is #1019 but with some minor nits and a bump needed to make CI pass.
=> Parse unsafe attributes

src/bindgen/ir/ty.rs, tests/expectations/unsafe_cell.c, tests/expectations/unsafe_cell.compat.c, tests/expectations/unsafe_cell.cpp, tests/expectations/unsafe_cell.pyx, tests/expectations/unsafe_cell_both.c, tests/expectations/unsafe_cell_both.compat.c, tests/expectations/unsafe_cell_tag.c, tests/expectations/unsafe_cell_tag.compat.c, tests/expectations/unsafe_cell_tag.pyx, tests/rust/unsafe_cell.rs
=> ir: add support for UnsafeCell and SyncUnsafeCell
